In [1]:
import numpy as np
import pandas as pd

In [4]:
phenotypes_data=pd.read_csv("data/phenotypes.tsv",sep='\t')
vegetation_data=pd.read_csv("data/vegetation.tsv",sep='\t')

In [5]:
data = pd.merge(phenotypes_data, vegetation_data, on=["sample"])
data

      sample   2015  2016   2017   2019   2020   2021  2022  2023  vegetation
0   PS000196    NaN   NaN    NaN   99.0    NaN    NaN   NaN   NaN         100
1   PS000195    NaN   NaN    NaN  100.0    NaN    NaN   NaN   NaN         103
2   PS000121    NaN   NaN  101.0  107.0    NaN    NaN   NaN   NaN         104
3   PS000126    NaN   NaN    NaN  115.0  112.0    NaN   NaN   NaN         106
4   PS000123    NaN   NaN    NaN  113.0  102.0   79.0   NaN   NaN         101
..       ...    ...   ...    ...    ...    ...    ...   ...   ...         ...
94  PS000370    NaN   NaN    NaN    NaN    NaN  128.0  85.0   NaN         118
95  PS000184  101.0  98.0   95.0   95.0   79.0   95.0   NaN   NaN         102
96  PS000169  122.0   NaN  121.0  120.0  151.0    NaN   NaN   NaN         114
97  PS000053    NaN   NaN  105.0   98.0    NaN    NaN   NaN   NaN         119
98  PS000200    NaN   NaN    NaN  100.0    NaN    NaN   NaN   NaN         116

[99 rows x 10 columns]

In [10]:
from bioinfokit.analys import marker

# id is for column name with chromosome identifier in VCF file
vcf_iter = marker.vcfreader(file='data/genotypes.vcf', id='#CHROM')

header_list = []
info_lines_list = []
marker_lines_list = []

# read vcf file
for record in vcf_iter:

    # get info lines, header, and variant records
    headers, info_lines, marker_lines = record

    header_list.append(headers)
    info_lines_list.append(info_lines)
    marker_lines_list.append(marker_lines)

In [11]:
header_list = header_list[0]
info_lines_list = info_lines_list[0]

In [12]:
info_lines_list[-24:]

['##contig=<ID=KZ848287,length=1002>',
 '##ALT=<ID=*,Description="Represents allele(s) other than observed.">',
 '##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">',
 '##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of raw reads supporting an indel">',
 '##INFO=<ID=IMF,Number=1,Type=Float,Description="Maximum fraction of raw reads supporting an indel">',
 '##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">',
 '##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">',
 '##INFO=<ID=RPB,Number=1,Type=Float,Description="Mann-Whitney U test of Read Position Bias (bigger is better)">',
 '##INFO=<ID=MQB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality Bias (bigger is better)">',
 '##INFO=<ID=BQB,Number=1,Type=Float,Description="Mann-Whitney U test of Base Quality Bias (bigger is better)">',
 '##INFO=<ID=MQSB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality vs Strand Bias (bigger is better)">',
 '##INFO=<ID=SGB,Number=1,Type=Float,Description="Segregation based metric.">',
 '##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">',
 '##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">',
 '##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Number of high-quality bases">',
 '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">',
 '##INFO=<ID=ICB,Number=1,Type=Float,Description="Inbreeding Coefficient Binomial test (bigger is better)">',
 '##INFO=<ID=HOB,Number=1,Type=Float,Description="Bias in the number of HOMs number (smaller is better)">',
 '##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">',
 '##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">',
 '##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">',
 '##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">',
 '##bcftools_callVersion=1.10.2+htslib-1.10.2-3ubuntu0.1',
 '##bcftools_concatVersion=1.10.2+htslib-1.10.2-3ubuntu0.1']

In [13]:
# Создание словаря
contig_dict = {}

for contig in info_lines_list[3:-23]:
    # Извлечение ID и length
    id_part = contig.split(',')[0].split('=')[2]  # Получаем ID
    length_part = contig.split(',')[1].split('=')[1][:-1]  # Получаем length
    contig_dict[id_part] = int(length_part)  # Добавляем в словарь

In [14]:
genotypes_data = pd.DataFrame(data=marker_lines_list, columns=header_list)
genotypes_data

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,PS000026,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
0,1,40481,.,G,A,132,.,.,GT:PL:DP,"0/0:0,3,39:1",...,"0/0:0,3,48:1","./.:0,0,0:0","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,9,151:3","0/0:0,27,220:9","0/0:0,66,250:22","0/0:0,47,247:20","0/0:0,99,251:33","0/0:0,60,250:20"
1,1,40522,.,C,T,999,.,.,GT:PL:DP,"0/0:0,3,40:1",...,"0/0:0,3,25:1","./.:0,0,0:0","0/0:0,3,37:1","0/0:0,3,37:1","0/0:0,9,92:3","0/0:0,27,170:9","0/0:0,66,196:22","0/0:0,47,193:20","0/0:0,99,199:33","0/0:0,57,195:19"
2,1,111641,.,G,C,999,.,.,GT:PL:DP,"0/1:39,3,0:1",...,"./.:0,0,0:0","0/1:48,3,0:1","0/1:255,0,24:12","0/1:191,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,223:56","0/0:0,21,254:7","0/1:255,0,194:37","0/0:0,39,255:13"
3,1,111675,.,G,C,999,.,.,GT:PL:DP,"0/1:49,3,0:1",...,"./.:0,0,0:0","0/1:60,3,0:1","0/1:255,0,24:12","0/1:197,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,221:56","0/0:0,21,254:7","0/1:255,0,229:38","0/0:0,39,255:13"
4,1,111688,.,T,C,999,.,.,GT:PL:DP,"0/1:40,3,0:1",...,"./.:0,0,0:0","0/1:60,3,0:1","0/1:255,0,24:12","0/1:197,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,223:56","0/0:0,21,254:7","0/1:255,0,226:38","0/0:0,39,255:13"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38935,KZ848124,2425,.,T,A,999,.,.,GT:PL:DP,"0/1:32,0,123:7",...,"0/1:55,0,151:14","0/1:103,0,131:12","0/1:166,0,151:42","0/1:100,0,129:13","0/1:166,0,146:34","0/0:0,33,41:11","0/1:153,0,87:37","0/1:165,0,143:80","0/1:158,0,163:51","0/1:161,0,191:83"
38936,KZ848124,2494,.,T,C,999,.,.,GT:PL:DP,"0/1:35,0,159:7",...,"0/1:58,0,252:14","0/1:110,0,205:12","0/1:232,0,255:42","0/1:127,0,193:12","0/1:178,0,255:35","./.:0,0,0:0","0/1:175,0,255:103","0/1:222,0,255:121","0/1:132,0,255:76","0/1:176,0,255:134"
38937,KZ848124,2502,.,T,A,999,.,.,GT:PL:DP,"0/0:0,21,150:7",...,"0/0:0,42,255:14","0/1:51,0,205:12","0/0:0,126,255:42","0/1:59,0,207:12","0/0:0,105,255:35","0/0:0,6,8:2","0/0:0,255,255:103","0/0:0,255,255:122","0/0:0,32,255:77","0/0:0,255,255:134"
38938,KZ848124,2515,.,G,T,999,.,.,GT:PL:DP,"0/0:0,21,149:7",...,"0/1:27,0,239:14","0/0:0,36,255:12","0/0:0,32,255:42","0/1:59,0,209:12","0/0:0,57,255:35","0/0:0,6,9:2","0/0:0,54,255:103","0/1:41,0,250:122","0/0:0,14,255:76","0/1:56,0,255:134"
38939,KZ848124,2552,.,A,C,999,.,.,GT:PL:DP,"0/1:15,0,124:7",...,"0/1:55,0,151:14","0/1:103,0,131:12","0/1:164,0,146:42","0/1:103,0,131:12","0/1:165,0,150:35","0/0:6,6,0:3","0/1:161,0,173:103","0/1:171,0,172:122","0/1:117,0,156:77","0/1:126,0,168:117"

In [15]:
genotypes_data.drop(columns=["ID", "FILTER", "INFO", "FORMAT"], inplace=True)

In [17]:
genotypes_data.to_csv("genotypes_processed.csv", index=False)

In [18]:
genotypes_data["PS000433"].str.split(":").str[0].unique()

array(['0/0', './.', '0/1', '1/1', '1/2', '0/2', '1/3', '2/2', '0/3'],
      dtype=object)

In [19]:
genotypes_data[genotypes_data["QUAL"].astype(float) < 100]

,#CHROM,POS,REF,ALT,QUAL,PS000026,PS000027,PS000028,PS000031,PS000033,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
149,1,3599872,CAAAAAAAA,CAAAAAAAAA,80,"0/0:0,3,12:1","0/0:0,24,52:8","0/0:0,114,62:38","0/0:0,78,68:27","1/1:36,23,0:19",...,"0/0:0,12,27:4","./.:0,0,0:0","0/0:0,96,56:32","0/0:0,18,36:6","0/0:0,90,57:30","0/0:0,187,47:62","./.:0,0,0:0","0/0:0,175,48:58","0/0:24,24,11:128","0/0:0,255,42:114"
298,1,8074821,CTCT,C,39.1211,"0/0:0,6,47:2","0/0:0,48,200:16","0/0:0,78,227:26","0/0:3,0,86:20","0/0:0,78,254:26",...,"0/0:0,27,76:9","0/0:0,6,35:2","0/0:0,7,35:8","0/0:0,33,163:11","0/0:0,60,152:20","0/1:9,0,50:8","0/0:0,111,159:38","0/0:0,99,203:34","0/0:0,102,215:34","0/0:0,22,113:17"
317,1,11292121,T,A,51,"./.:0,0,0:0","0/0:4,0,28:4","0/0:0,24,96:8","0/0:0,5,56:7","0/0:0,21,106:7",...,"./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","0/0:0,36,182:12","0/0:0,45,187:15","0/0:0,36,182:12","0/0:0,27,163:9","0/0:0,24,159:8"
326,1,13209987,A,C,91,"0/0:0,6,7:2","0/0:0,51,9:17","0/0:0,33,12:11","./.:0,0,0:0","0/0:0,75,7:25",...,"0/0:0,9,9:3","0/0:0,3,4:1","0/0:0,33,12:11","0/0:0,6,7:2","0/0:0,12,11:4","0/0:0,9,9:3","0/0:0,72,7:24","0/0:0,78,7:26","./.:0,0,0:0","./.:0,0,0:0"
442,1,18327660,G,A,50,"./.:0,0,0:0","./.:0,0,0:0","0/1:12,3,0:1","0/0:0,3,40:1","0/1:2,0,90:10",...,"./.:0,0,0:0","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,12,176:4","0/0:0,15,212:5","0/0:0,18,205:6","0/0:0,15,255:11","0/0:0,24,255:8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38346,KZ847136,567123,C,T,99,"0/1:0,3,4:1","0/1:0,3,9:1","0/0:0,6,7:2","0/0:0,18,20:6","0/0:0,5,6:11",...,"./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","0/1:0,3,4:1","0/1:0,1,7:2","0/1:0,3,9:1","0/1:0,3,4:1","0/1:0,3,4:1","0/0:0,15,58:5","0/1:0,3,4:1"
38359,KZ847139,286923,A,G,39.7275,"0/1:0,1,0:2","0/0:0,9,9:3","1/1:7,30,0:17","1/1:8,66,0:22","0/0:0,75,7:25",...,"1/1:6,32,0:21","1/1:1,6,0:16","1/1:1,23,0:84","1/1:2,32,0:58","1/1:3,43,0:100","0/0:0,81,5:32","1/1:9,54,0:18","0/0:0,105,6:35","0/0:0,216,9:78","1/1:1,17,0:69"
38670,KZ847789,1062,A,C,98,"0/0:0,6,60:2","0/1:8,0,40:8","0/0:0,23,102:25","0/0:0,35,117:19","0/0:0,23,161:21",...,"0/0:0,3,123:9","0/0:0,5,22:4","0/0:0,5,255:28","0/0:0,4,208:13","0/0:0,29,255:42","0/0:0,71,255:150","0/0:0,65,255:54","0/0:0,79,255:61","0/0:0,68,255:39","0/0:0,171,255:100"
38836,KZ847539,1292,C,G,43.6996,"1/1:9,9,0:3","0/1:0,1,0:2","1/1:9,9,0:3","0/0:0,4,2:7","0/1:0,3,3:3",...,"./.:0,0,0:0","0/1:0,3,4:1","0/1:0,3,3:3","1/1:4,3,0:1","1/1:4,3,0:1","./.:0,0,0:0","./.:0,0,0:0","1/1:7,6,0:2","1/1:10,48,0:16","1/1:8,16,0:11"
38910,KZ848124,549,A,T,92,"0/0:0,3,9:1","0/0:4,3,0:1","0/1:12,0,21:7","0/1:57,0,21:11","0/0:0,18,47:9",...,"1/1:31,10,0:13","0/0:0,9,9:3","0/0:0,20,2:36","0/0:2,8,0:18","0/0:0,13,1:51","./.:0,0,0:0","0/0:0,25,2:72","0/0:0,16,1:93","0/0:0,72,3:80","0/0:0,31,2:89"

In [20]:
genotypes_data = pd.read_csv("genotypes_processed.csv")

C:\Users\egorm\AppData\Local\Temp\ipykernel_42536\3591413676.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  genotypes_data = pd.read_csv("genotypes_processed.csv")

In [34]:
def set_nans(min_experiments: int, min_diff: int):
    genotypes_data_exp = genotypes_data.copy()
    
    for column in genotypes_data_exp.columns[5:]:
        split_data = genotypes_data_exp[column].str.split(":", expand=True)

        ids1 = split_data[2].astype(int) < min_experiments
        
        second_values = split_data[1].str.split(",").apply(lambda x: [int(i) for i in x] if isinstance(x, list) else [])
        
        second_largest = second_values.apply(lambda x: sorted(x)[-2] if len(x) > 1 else np.nan)
        ids2 = second_largest < min_diff

        genotypes_data_exp[column] = genotypes_data_exp[column].str.split(":").str[0]
        genotypes_data_exp.loc[ids1 | ids2, column] = "./."

    return genotypes_data_exp

gen_d_exp = set_nans(min_experiments=15, min_diff=20)
gen_d_exp

,#CHROM,POS,REF,ALT,QUAL,PS000026,PS000027,PS000028,PS000031,PS000033,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
0,1,40481,G,A,132.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/0,0/0,0/0,0/0
1,1,40522,C,T,999.0,./.,./.,0/1,0/0,0/1,...,./.,./.,./.,./.,./.,./.,0/0,0/0,0/0,0/0
2,1,111641,G,C,999.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/1,./.,0/1,./.
3,1,111675,G,C,999.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/1,./.,0/1,./.
4,1,111688,T,C,999.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/1,./.,0/1,./.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38935,KZ848124,2425,T,A,999.0,./.,0/1,0/1,0/1,0/1,...,./.,./.,0/1,./.,0/1,./.,0/1,0/1,0/1,0/1
38936,KZ848124,2494,T,C,999.0,./.,0/1,0/1,0/1,0/1,...,./.,./.,0/1,./.,0/1,./.,0/1,0/1,0/1,0/1
38937,KZ848124,2502,T,A,999.0,./.,0/0,0/1,0/0,0/1,...,./.,./.,0/0,./.,0/0,./.,0/0,0/0,0/0,0/0
38938,KZ848124,2515,G,T,999.0,./.,0/0,./.,./.,./.,...,./.,./.,0/0,./.,0/0,./.,0/0,0/1,./.,0/1
38939,KZ848124,2552,A,C,999.0,./.,0/1,0/1,0/1,0/1,...,./.,./.,0/1,./.,0/1,./.,0/1,0/1,0/1,0/1

In [22]:
gen_d_exp.to_csv("genotypes_processed_fixed_feat_values3.csv", index=False)

In [23]:
time_data = pd.read_csv("Data.csv")
time_data = time_data[~time_data["value"].isna()]
time_data.head()

    Unnamed: 0    sample  year  value
14          14  PS000076  2015  114.0
15          15  PS000033  2015  116.0
16          16  PS000048  2015   99.0
17          17  PS000191  2015   71.0
18          18  PS000077  2015   90.0

In [24]:
gen_to_merge = gen_d_exp.iloc[:, 5:].T.reset_index().rename(columns={"index": "sample"})
gen_to_merge.columns = gen_to_merge.columns.astype(str)
gen_to_merge

,sample,0,1,2,3,4,5,6,7,8,...,38930,38931,38932,38933,38934,38935,38936,38937,38938,38939
0,PS000026,./.,./.,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,./.,./.,./.,./.,./.,./.,./.
1,PS000027,./.,./.,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/0,0/0,0/1
2,PS000028,./.,0/1,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/1,./.,0/1
3,PS000031,./.,0/0,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/0,./.,0/1
4,PS000033,./.,0/1,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,0/0,0/1,0/1,0/1,0/1,0/1,./.,0/1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,PS000444,./.,./.,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/0,./.,./.,./.,./.,./.,./.,./.,./.
95,PS000566,0/0,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/1,...,0/0,./.,./.,0/1,0/1,0/1,0/1,0/0,0/0,0/1
96,PS000567,0/0,0/0,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/0,0/1,0/1
97,PS000568,0/0,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/1,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/0,./.,0/1
98,PS000570,0/0,0/0,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/0,0/1,0/1

In [25]:
count_dots = gen_to_merge.apply(lambda col: (col == './.').sum())
count_dots

sample     0
0         93
1         75
2         89
3         89
          ..
38935     32
38936     33
38937     45
38938     55
38939     37
Length: 38941, dtype: int64

In [26]:
np.sum(count_dots) / 38940 / 99, np.sum(count_dots <= 50), np.sum(count_dots <= 33)

(0.7874165382639958, 5963, 2973)

In [27]:
gen_to_merge = gen_to_merge.loc[:, count_dots <= 15]
gen_to_merge

,sample,19,69,70,241,243,686,687,688,689,...,38883,38900,38902,38922,38925,38927,38928,38929,38930,38931
0,PS000026,1/1,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,./.,0/1,0/0,0/1,0/1,0/1,0/1,0/1,0/0,0/1
1,PS000027,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/1,0/1,0/1,0/1,0/1,./.,0/1,0/1,0/0,0/1
2,PS000028,0/1,0/1,0/1,0/0,0/1,0/1,0/1,0/1,0/1,...,0/1,0/1,0/0,0/1,0/1,0/1,0/1,0/1,0/0,0/1
3,PS000031,1/1,1/1,1/1,./.,1/1,0/1,0/1,0/1,0/1,...,./.,0/1,0/0,0/1,0/1,0/1,./.,./.,0/0,0/1
4,PS000033,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,0/1,0/1,0/1,0/1,0/1,0/0,0/1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,PS000444,0/0,0/0,0/0,0/0,1/1,0/1,0/1,0/1,0/1,...,0/0,./.,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
95,PS000566,1/1,1/1,1/1,0/0,1/1,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,./.,0/1,0/1,0/0,0/0,0/0,./.
96,PS000567,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/0,./.,0/0,./.,0/1,0/0,0/0,0/0,0/0,0/1
97,PS000568,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,0/1,0/1,0/1,0/1,./.,0/0,0/1
98,PS000570,1/1,0/0,0/0,0/0,1/1,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,0/0,0/1,0/0,0/0,0/0,0/0,0/1

In [28]:
weather_features = pd.read_csv("Weather features.csv").drop(index=[0,1]).rename(columns={"Unnamed: 0": "year"})
weather_features["year"] = weather_features["year"].astype(int)
weather_features

,year,Т(С),Т(С).1,Т(С).2,Т(С).3,Т(С).4,Тd(С),Тd(С).1,Тd(С).2,Тd(С).3,...,P(гПа).4,Po(гПа),Po(гПа).1,Po(гПа).2,Po(гПа).3,Po(гПа).4,T_critical_days,T_nogrowth_days,T_middling_days,T_optimal_days
2,2015,16.314113,21.207917,20.712903,19.155645,17.365000,6.395565,12.598750,13.577016,9.640726,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
3,2016,15.308065,19.803750,22.849194,22.140323,12.684167,9.516129,12.635000,13.895968,14.306452,...,1013.996250,994.500403,996.538333,993.798387,997.894758,995.515833,6.0,153.0,77.0,63.0
4,2017,13.699597,17.378750,20.678629,21.430364,14.940000,4.881452,9.879167,12.282661,12.314919,...,1020.126250,995.589919,991.655000,993.020161,998.868952,1001.658750,4.0,152.0,68.0,68.0
5,2019,16.822177,21.674583,18.652419,19.162500,14.319167,10.193145,12.939583,11.627016,10.886694,...,1016.910833,984.478629,988.383750,980.197984,987.036290,987.538333,1.0,153.0,66.0,77.0
6,2020,11.643145,20.985000,20.670565,19.255870,16.767083,5.518548,12.094167,10.802016,9.393522,...,1018.748333,982.829839,984.382083,984.293145,985.496761,989.552917,2.0,152.0,71.0,70.0
7,2021,14.677419,20.178750,23.121371,21.951210,11.343460,6.930645,13.018750,14.190323,12.776210,...,1016.192405,983.374194,985.202917,984.912097,984.665323,986.634599,6.0,152.0,69.0,65.0
8,2022,12.164113,20.039167,19.782661,22.075000,10.915063,2.420161,12.036250,13.608065,13.455242,...,1012.734728,984.718952,985.620417,984.626210,988.247177,983.189121,1.0,152.0,75.0,66.0
9,2023,14.301210,17.400000,19.855645,21.335081,16.441250,4.266129,9.677917,14.416532,15.326613,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0

In [29]:
final_dataset = pd.merge(pd.merge(time_data, gen_to_merge, on=["sample"]), weather_features, on=["year"])
final_dataset

,Unnamed: 0,sample,year,value,19,69,70,241,243,686,...,P(гПа).4,Po(гПа),Po(гПа).1,Po(гПа).2,Po(гПа).3,Po(гПа).4,T_critical_days,T_nogrowth_days,T_middling_days,T_optimal_days
0,14,PS000076,2015,114.0,0/0,./.,./.,0/1,1/1,./.,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
1,15,PS000033,2015,116.0,0/0,0/0,0/0,0/0,0/0,0/1,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
2,16,PS000048,2015,99.0,0/0,0/0,0/0,0/0,0/0,0/1,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
3,17,PS000191,2015,71.0,0/0,0/0,0/0,0/0,0/0,0/1,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
4,18,PS000077,2015,90.0,./.,0/0,0/0,0/1,1/1,./.,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,701,PS000570,2023,91.0,1/1,0/0,0/0,0/0,1/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
355,703,PS000440,2023,130.0,0/0,0/0,0/0,0/0,1/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
356,748,PS000444,2023,113.0,0/0,0/0,0/0,0/0,1/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
357,780,PS000433,2023,119.0,0/0,0/0,0/0,0/0,1/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
358,784,PS000436,2023,110.0,./.,./.,./.,0/0,1/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0

In [30]:
final_dataset.to_csv("final_dataset.csv", index=False)

In [31]:
X, y = final_dataset.drop(columns=["value", "sample"]), final_dataset["value"]

In [32]:
cat_features = np.array(gen_to_merge.columns[1:]).astype(str)
cat_features[:5]

array(['19', '69', '70', '241', '243'], dtype='<U5')

In [36]:
from category_encoders.cat_boost import CatBoostEncoder

In [37]:
cbe_encoder = CatBoostEncoder() 
  
# Fit encoder and transform the features 
cbe_encoder.fit(X.loc[:, cat_features], y) 
X.loc[:, cat_features] = cbe_encoder.transform(X.loc[:, cat_features]) 
X.head()

C:\Users\egorm\AppData\Local\Temp\ipykernel_42536\468688771.py:5: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.loc[:, cat_features] = cbe_encoder.transform(X.loc[:, cat_features])

,Unnamed: 0,year,19,69,70,241,243,686,687,688,...,P(гПа).4,Po(гПа),Po(гПа).1,Po(гПа).2,Po(гПа).3,Po(гПа).4,T_critical_days,T_nogrowth_days,T_middling_days,T_optimal_days
0,14,2015,104.364766,103.356604,103.356604,104.790189,104.970288,102.041370,102.041370,102.041370,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
1,15,2015,104.364766,104.926913,104.926913,104.016337,102.637182,104.284781,104.284781,104.284781,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
2,16,2015,104.364766,104.926913,104.926913,104.016337,102.637182,104.284781,104.284781,104.284781,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
3,17,2015,104.364766,104.926913,104.926913,104.016337,102.637182,104.284781,104.284781,104.284781,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
4,18,2015,105.359232,104.926913,104.926913,104.790189,104.970288,102.041370,102.041370,102.041370,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0

In [38]:
X.columns = X.columns.astype(str)

In [39]:
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Создание и обучение модели CatBoost
model = CatBoostRegressor(iterations=1000,  # количество итераций
                          learning_rate=0.1,  # скорость обучения
                          depth=6,  # глубина деревьев
                          eval_metric='MAE',  # метрика для оценки
                          verbose=100)  # вывод информации каждые 100 итераций

model.fit(X_train, y_train)

# Прогнозирование на тестовой выборке
y_pred = model.predict(X_test)

# Расчет метрик
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Вывод результатов
print(f'Mean Absolute Error (MAE): {mae:.2f}')
print(f'R² Score: {r2:.4f}')

0:	learn: 11.6379833	total: 112ms	remaining: 1m 51s
100:	learn: 4.8435721	total: 664ms	remaining: 5.91s
200:	learn: 1.8728516	total: 1.16s	remaining: 4.6s
300:	learn: 0.8106313	total: 1.62s	remaining: 3.77s
400:	learn: 0.3705450	total: 2.13s	remaining: 3.17s
500:	learn: 0.1720728	total: 2.66s	remaining: 2.65s
600:	learn: 0.0805452	total: 3.14s	remaining: 2.08s
700:	learn: 0.0396617	total: 3.65s	remaining: 1.55s
800:	learn: 0.0208721	total: 4.22s	remaining: 1.05s
900:	learn: 0.0107886	total: 4.74s	remaining: 520ms
999:	learn: 0.0055774	total: 5.2s	remaining: 0us
Mean Absolute Error (MAE): 11.51
R² Score: 0.2425

In [40]:
feature_importances = model.get_feature_importance()
feature_importances

array([5.55821776e+00, 0.00000000e+00, 1.98937364e-02, 1.39605297e-01,
       3.06677155e-01, 2.23290563e-02, 9.24054831e-02, 0.00000000e+00,
       4.47168530e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 8.20114836e-02, 0.00000000e+00, 0.00000000e+00,
       5.98039105e-03, 3.26950087e-01, 0.00000000e+00, 2.45036617e-02,
       1.28574664e-01, 7.60676269e-04, 1.03629923e-01, 6.04331442e-05,
       1.87620533e-01, 0.00000000e+00, 5.61959260e-02, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.11580730e-01,
       1.18723402e-04, 2.10526347e-01, 1.17781402e-01, 7.67646062e-04,
       7.11132972e-03, 4.76693411e-07, 2.25235964e-01, 4.04040396e-02,
       3.11483281e-01, 3.97580631e-02, 7.25634228e-02, 9.35936744e-01,
       5.93977333e-01, 1.80212135e-04, 1.23663877e-03, 1.44926393e-02,
       4.30789466e-01, 1.79166471e-01, 7.34424975e-01, 8.78773452e-02,
       0.00000000e+00, 1.58688827e-01, 7.28458302e-01, 5.63045130e-01,
       4.25346120e-03, 3.70217902e-01, 2.47491299e-02, 2.97481416e-05,
       0.00000000e+00, 0.00000000e+00, 1.86953232e-02, 2.60839054e-02,
       0.00000000e+00, 1.89942020e-02, 0.00000000e+00, 1.39771599e-01,
       2.41739511e-02, 3.61131914e-03, 3.58368185e-03, 9.85444408e-03,
       0.00000000e+00, 0.00000000e+00, 2.26535705e-02, 6.56076734e-02,
       1.18254850e-01, 7.50498887e-02, 1.00631344e-01, 6.82063603e-02,
       4.12911033e-02, 2.23076611e-01, 5.18422302e-01, 7.96579707e-01,
       7.38405507e-01, 3.13735008e-02, 2.21363052e-06, 8.27285665e-06,
       2.34846259e-01, 5.99504653e-02, 1.81164827e-01, 2.37442686e-01,
       4.39417859e-02, 1.39841086e-01, 1.50245996e-06, 4.50960277e-01,
       2.92701519e-01, 1.58833842e-01, 4.08989417e-06, 4.10395481e-03,
       1.39261156e-01, 1.85279907e-01, 4.68746998e-01, 3.67641449e-04,
       0.00000000e+00, 1.18015264e-02, 6.35932494e-01, 2.04468335e-01,
       1.46827785e-07, 1.74474980e-01, 4.19819847e-01, 1.02323011e-01,
       9.30295415e-02, 3.67239687e-02, 1.71710483e-01, 3.92663033e-01,
       7.00285799e-01, 5.89554472e-06, 6.07233423e-02, 1.20396505e-05,
       2.52057154e-02, 0.00000000e+00, 5.96493713e-05, 3.56832592e-08,
       2.31264787e-07, 7.67892664e-02, 1.12762786e-01, 4.62155921e-06,
       3.91705881e-02, 1.09594419e-01, 1.27179915e-03, 6.84784957e-01,
       8.04529993e-02, 1.08796045e-01, 3.21921700e-01, 2.32440727e-01,
       4.44922187e-01, 1.63011191e-01, 9.25778638e-02, 9.51870861e-04,
       6.49123743e-02, 3.73073291e-04, 1.29395369e-01, 1.73855034e-01,
       2.14615104e-01, 3.21807128e-01, 1.47474709e-01, 3.03743083e-01,
       2.02771263e-01, 4.73292642e-02, 1.36291361e-01, 9.77769136e-02,
       0.00000000e+00, 2.97394114e-03, 1.22446022e-02, 3.95234042e-02,
       1.27905128e-01, 8.55519701e-03, 6.20516822e-05, 1.51123700e-03,
       2.38198652e-01, 1.02857456e-02, 1.27206235e-01, 3.66208300e-01,
       1.86318935e-01, 5.37899244e-01, 6.14803910e-03, 1.98036092e-03,
       9.59009620e-05, 0.00000000e+00, 0.00000000e+00, 6.73037428e-04,
       1.63115017e-02, 1.38721673e-01, 3.45066277e-01, 5.24268495e-07,
       3.01100256e-05, 2.89924447e-05, 1.25964086e-04, 3.42013097e-01,
       0.00000000e+00, 1.12951705e-02, 4.92234564e-02, 7.11398592e-02,
       7.77233812e-03, 0.00000000e+00, 2.73539606e-03, 5.24301239e-01,
       1.01915981e-03, 1.31170944e-01, 6.16982396e-02, 2.30343363e-01,
       4.80732009e-03, 4.62754092e-02, 7.54434530e-01, 1.38681171e-01,
       1.84975750e-01, 5.75970004e-03, 2.78620580e-01, 4.65532401e-06,
       3.31421783e-05, 8.02630001e-05, 7.05710720e-01, 4.30227131e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.27262949e-01,
       0.00000000e+00, 2.84863915e-01, 7.04531747e-03, 8.58407380e-03,
       1.98949193e-03, 8.48185285e-03, 0.00000000e+00, 7.21639864e-02,
       0.00000000e+00, 6.23250162e-02, 1.30567407e-01, 1.75296234e-01,
       2.69461351e-01, 1.69157485e+00, 2.26928481e-03, 0.00000000e+00,
       1.16661902e-01, 2.77480500e-01, 0.00000000e+00, 0.00000000e+00,
       1.77992172e-04, 3.76942751e-01, 2.43960656e-01, 7.32737982e-07,
       1.37685277e-01, 4.58095092e-03, 6.83550472e-04, 2.13881784e-02,
       0.00000000e+00, 1.66577740e-04, 2.11604595e-01, 9.73240116e-06,
       2.81607206e-02, 7.08321325e-02, 4.05663991e-03, 0.00000000e+00,
       1.60898848e-05, 0.00000000e+00, 3.34487735e-01, 2.79363681e-01,
       2.67418719e-02, 3.51935580e-01, 3.88283074e-01, 2.75921379e-02,
       1.09603151e-03, 9.14205020e-02, 0.00000000e+00, 1.41753429e-01,
       0.00000000e+00, 3.77419058e-01, 0.00000000e+00, 3.85481289e-01,
       1.25455766e-01, 4.87113675e-04, 5.62399447e-03, 3.14931066e-02,
       4.06613670e-05, 1.17357639e-03, 7.58887506e-02, 6.69946675e-01,
       0.00000000e+00, 1.14394313e-01, 0.00000000e+00, 1.01449387e-02,
       0.00000000e+00, 0.00000000e+00, 1.29574619e-02, 1.21072019e-03,
       5.97077059e-01, 2.35995530e-01, 3.07916674e-03, 1.41279900e-04,
       2.20188393e-01, 8.16288941e-04, 1.49504674e-01, 9.39078317e-07,
       2.63321379e-02, 1.24019125e-01, 3.96737727e-01, 8.17674776e-01,
       3.00744693e-02, 3.97779099e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.52195151e-01, 1.74159689e-01, 4.10128156e-01,
       2.68179670e-03, 2.79435800e+00, 6.71460514e-02, 1.30551304e-02,
       5.80259905e-04, 1.06287730e-01, 7.08225463e-02, 2.59915235e-01,
       4.53446286e-09, 4.82871764e-04, 7.56203875e-01, 3.11099522e-01,
       0.00000000e+00, 4.57616480e-01, 2.80940527e-01, 4.09300038e-01,
       7.99871472e-01, 4.25093402e-04, 1.61278920e-01, 3.54396328e-06,
       1.47547717e-02, 1.52815807e-02, 3.09493204e-01, 1.51740018e-02,
       1.11678565e-03, 0.00000000e+00, 1.73020148e-03, 1.50205610e-01,
       1.24874686e-02, 5.79424817e-02, 4.80122203e-01, 1.48274450e-01,
       7.48327958e-03, 8.54434510e-02, 0.00000000e+00, 1.22830802e-02,
       4.73263353e-02, 3.57985937e-02, 5.13718439e-02, 1.47290023e-01,
       9.15690832e-02, 3.33486051e-01, 9.30105655e-01, 8.63989363e-02,
       2.59737310e-03, 7.86636690e-02, 2.46724620e-01, 2.46512920e-01,
       1.53140172e-01, 4.61939107e-02, 2.31805657e-02, 1.33293285e-02,
       1.76356387e-04, 2.87214320e-01, 1.34561968e+00, 2.22005595e-01,
       5.60643796e-01, 4.09421769e-01, 9.66972113e-02, 1.48579422e-05,
       1.47993902e-01, 2.93667693e-02, 4.09182641e-02, 1.57571111e-03,
       1.67806693e-04, 7.87407111e-03, 6.70950842e-05, 1.44119884e-02,
       1.98078471e-01, 7.31074965e-03, 1.64730824e-03, 1.74946174e-04,
       1.53572312e-01, 2.43816111e-01, 1.20443350e-01, 3.91209734e-01,
       1.31859739e-03, 1.42638106e+00, 2.07744513e-01, 9.42402768e-02,
       1.25278971e+00, 1.41382403e-01, 1.44190888e-01, 1.48287028e-02,
       4.51688864e-01, 1.78453174e-01, 4.02950938e-03, 1.10242358e-05,
       0.00000000e+00, 5.14262724e-03, 1.64965022e-01, 4.30004627e-04,
       8.82740599e-02, 1.51752736e-01, 1.16184570e+00, 1.98029597e-04,
       2.56680067e-01, 0.00000000e+00, 7.89935834e-02, 1.12427400e-01,
       0.00000000e+00, 0.00000000e+00, 3.55115113e-06, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.26522397e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.75622216e-04,
       0.00000000e+00, 3.71259088e-02, 5.95486469e-02, 7.15907260e-02,
       1.52532310e-01, 5.93875542e-01, 5.92091276e-04, 2.18340597e-01,
       1.99698949e-01, 1.69909191e-02, 0.00000000e+00, 3.35163664e-01,
       8.34875997e-01, 2.26852328e-02, 1.86962143e-01, 2.49917882e-01,
       1.65488216e+00, 1.10315846e+00, 3.48618096e-01, 4.61410396e-01,
       4.53847382e-01, 2.50066451e-01, 2.03420804e-02, 3.49847780e-04,
       4.61316327e-02, 2.22108413e-03, 6.40360645e-02, 2.41454498e-01,
       6.79206673e-02, 9.35934241e-01, 6.16181119e-02, 0.00000000e+00,
       0.00000000e+00, 3.92114749e-02, 3.09046920e-01, 3.25436612e-01,
       1.03857176e+00, 4.17121507e-01, 1.71029863e-01, 9.89525088e-02,
       2.09559800e-01, 4.92651824e-01, 3.11601322e-05, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.66856068e-01,
       1.31091424e-01, 4.01231506e-03, 2.25095487e-04, 1.77690892e-01,
       2.57562996e-03, 2.44174634e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.15696565e-04, 2.38962942e-01,
       2.53066531e-01, 1.01822405e-01, 1.12401174e-01, 1.65017422e-02,
       1.00108842e-03, 2.30132054e-05, 6.19254194e-02, 4.00604427e-02,
       7.35209003e-02, 3.71068391e-01, 3.50164406e-05, 0.00000000e+00,
       2.40258806e-01, 2.07631200e-03, 1.30955293e-01, 4.44616502e-04,
       2.28400076e-02, 6.95591171e-01, 1.38086138e-04, 4.56978539e-03,
       5.96334093e-02, 9.76188889e-02, 1.36624157e+00, 7.70239848e-01,
       1.07892673e+00, 4.92249010e-01, 8.89103783e-03, 1.07440332e+00,
       2.89575647e-01, 2.17896929e-02, 2.58222975e-01, 6.14053323e-02,
       1.39808411e+00, 8.54587799e-02, 1.17108371e+00, 1.86605076e+00,
       5.15651250e-01, 7.22759640e-02, 7.98604988e-01, 8.12235427e-01,
       3.46831874e-01, 1.90728169e-01, 5.10826596e-01, 5.81194471e-01,
       6.74557445e-01, 5.06489401e-01, 2.50025127e-01, 1.26091439e-01,
       4.22654433e-01, 1.12898546e+00, 5.39016727e-01, 1.71516651e-01,
       1.13778257e+00, 0.00000000e+00, 7.13269334e-01, 5.13433829e-01,
       5.38937127e-02, 8.30932795e-03, 5.59776942e-02, 3.59681613e-01,
       6.12377862e-01])

In [41]:
feature_importances[np.argsort(feature_importances)][:4000]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.53446286e-09, 3.56832592e-08,
       1.46827785e-07, 2.31264787e-07, 4.76693411e-07, 5.24268495e-07,
       7.32737982e-07, 9.39078317e-07, 1.50245996e-06, 2.21363052e-06,
       3.54396328e-06, 3.55115113e-06, 4.08989417e-06, 4.62155921e-06,
       4.65532401e-06, 5.89554472e-06, 8.27285665e-06, 9.73240116e-06,
       1.10242358e-05, 1.20396505e-05, 1.48579422e-05, 1.60898848e-05,
       2.30132054e-05, 2.44174634e-05, 2.89924447e-05, 2.97481416e-05,
       3.01100256e-05, 3.11601322e-05, 3.31421783e-05, 3.50164406e-05,
       4.06613670e-05, 5.96493713e-05, 6.04331442e-05, 6.20516822e-05,
       6.70950842e-05, 8.02630001e-05, 9.59009620e-05, 1.18723402e-04,
       1.25964086e-04, 1.38086138e-04, 1.41279900e-04, 1.66577740e-04,
       1.67806693e-04, 1.74946174e-04, 1.76356387e-04, 1.77992172e-04,
       1.80212135e-04, 1.98029597e-04, 2.15696565e-04, 2.25095487e-04,
       3.49847780e-04, 3.67641449e-04, 3.73073291e-04, 3.75622216e-04,
       4.25093402e-04, 4.30004627e-04, 4.44616502e-04, 4.82871764e-04,
       4.87113675e-04, 5.80259905e-04, 5.92091276e-04, 6.73037428e-04,
       6.83550472e-04, 7.60676269e-04, 7.67646062e-04, 8.16288941e-04,
       9.51870861e-04, 1.00108842e-03, 1.01915981e-03, 1.09603151e-03,
       1.11678565e-03, 1.17357639e-03, 1.21072019e-03, 1.23663877e-03,
       1.26522397e-03, 1.27179915e-03, 1.31859739e-03, 1.51123700e-03,
       1.57571111e-03, 1.64730824e-03, 1.73020148e-03, 1.98036092e-03,
       1.98949193e-03, 2.07631200e-03, 2.22108413e-03, 2.26928481e-03,
       2.57562996e-03, 2.59737310e-03, 2.68179670e-03, 2.73539606e-03,
       2.97394114e-03, 3.07916674e-03, 3.58368185e-03, 3.61131914e-03,
       4.01231506e-03, 4.02950938e-03, 4.05663991e-03, 4.10395481e-03,
       4.25346120e-03, 4.30227131e-03, 4.56978539e-03, 4.58095092e-03,
       4.80732009e-03, 5.14262724e-03, 5.62399447e-03, 5.75970004e-03,
       5.98039105e-03, 6.14803910e-03, 7.04531747e-03, 7.11132972e-03,
       7.31074965e-03, 7.48327958e-03, 7.77233812e-03, 7.87407111e-03,
       8.30932795e-03, 8.48185285e-03, 8.55519701e-03, 8.58407380e-03,
       8.89103783e-03, 9.85444408e-03, 1.01449387e-02, 1.02857456e-02,
       1.12951705e-02, 1.18015264e-02, 1.22446022e-02, 1.22830802e-02,
       1.24874686e-02, 1.29574619e-02, 1.30551304e-02, 1.33293285e-02,
       1.44119884e-02, 1.44926393e-02, 1.47547717e-02, 1.48287028e-02,
       1.51740018e-02, 1.52815807e-02, 1.63115017e-02, 1.65017422e-02,
       1.69909191e-02, 1.86953232e-02, 1.89942020e-02, 1.98937364e-02,
       2.03420804e-02, 2.13881784e-02, 2.17896929e-02, 2.23290563e-02,
       2.26535705e-02, 2.26852328e-02, 2.28400076e-02, 2.31805657e-02,
       2.41739511e-02, 2.45036617e-02, 2.47491299e-02, 2.52057154e-02,
       2.60839054e-02, 2.63321379e-02, 2.67418719e-02, 2.75921379e-02,
       2.81607206e-02, 2.93667693e-02, 3.00744693e-02, 3.13735008e-02,
       3.14931066e-02, 3.57985937e-02, 3.67239687e-02, 3.71259088e-02,
       3.91705881e-02, 3.92114749e-02, 3.95234042e-02, 3.97580631e-02,
       4.00604427e-02, 4.04040396e-02, 4.09182641e-02, 4.12911033e-02,
       4.39417859e-02, 4.47168530e-02, 4.61316327e-02, 4.61939107e-02,
       4.62754092e-02, 4.73263353e-02, 4.73292642e-02, 4.92234564e-02,
       5.13718439e-02, 5.38937127e-02, 5.59776942e-02, 5.61959260e-02,
       5.79424817e-02, 5.95486469e-02, 5.96334093e-02, 5.99504653e-02,
       6.07233423e-02, 6.14053323e-02, 6.16181119e-02, 6.16982396e-02,
       6.19254194e-02, 6.23250162e-02, 6.40360645e-02, 6.49123743e-02,
       6.56076734e-02, 6.71460514e-02, 6.79206673e-02, 6.82063603e-02,
       7.08225463e-02, 7.08321325e-02, 7.11398592e-02, 7.15907260e-02,
       7.21639864e-02, 7.22759640e-02, 7.25634228e-02, 7.35209003e-02,
       7.50498887e-02, 7.58887506e-02, 7.67892664e-02, 7.86636690e-02,
       7.89935834e-02, 8.04529993e-02, 8.20114836e-02, 8.54434510e-02,
       8.54587799e-02, 8.63989363e-02, 8.78773452e-02, 8.82740599e-02,
       9.14205020e-02, 9.15690832e-02, 9.24054831e-02, 9.25778638e-02,
       9.30295415e-02, 9.42402768e-02, 9.66972113e-02, 9.76188889e-02,
       9.77769136e-02, 9.89525088e-02, 1.00631344e-01, 1.01822405e-01,
       1.02323011e-01, 1.03629923e-01, 1.06287730e-01, 1.08796045e-01,
       1.09594419e-01, 1.12401174e-01, 1.12427400e-01, 1.12762786e-01,
       1.14394313e-01, 1.16661902e-01, 1.17781402e-01, 1.18254850e-01,
       1.20443350e-01, 1.24019125e-01, 1.25455766e-01, 1.26091439e-01,
       1.27206235e-01, 1.27905128e-01, 1.28574664e-01, 1.29395369e-01,
       1.30567407e-01, 1.30955293e-01, 1.31091424e-01, 1.31170944e-01,
       1.36291361e-01, 1.37685277e-01, 1.38681171e-01, 1.38721673e-01,
       1.39261156e-01, 1.39605297e-01, 1.39771599e-01, 1.39841086e-01,
       1.41382403e-01, 1.41753429e-01, 1.44190888e-01, 1.47290023e-01,
       1.47474709e-01, 1.47993902e-01, 1.48274450e-01, 1.49504674e-01,
       1.50205610e-01, 1.51752736e-01, 1.52532310e-01, 1.53140172e-01,
       1.53572312e-01, 1.58688827e-01, 1.58833842e-01, 1.61278920e-01,
       1.63011191e-01, 1.64965022e-01, 1.66856068e-01, 1.71029863e-01,
       1.71516651e-01, 1.71710483e-01, 1.73855034e-01, 1.74159689e-01,
       1.74474980e-01, 1.75296234e-01, 1.77690892e-01, 1.78453174e-01,
       1.79166471e-01, 1.81164827e-01, 1.84975750e-01, 1.85279907e-01,
       1.86318935e-01, 1.86962143e-01, 1.87620533e-01, 1.90728169e-01,
       1.98078471e-01, 1.99698949e-01, 2.02771263e-01, 2.04468335e-01,
       2.07744513e-01, 2.09559800e-01, 2.10526347e-01, 2.11580730e-01,
       2.11604595e-01, 2.14615104e-01, 2.18340597e-01, 2.20188393e-01,
       2.22005595e-01, 2.23076611e-01, 2.25235964e-01, 2.27262949e-01,
       2.30343363e-01, 2.32440727e-01, 2.34846259e-01, 2.35995530e-01,
       2.37442686e-01, 2.38198652e-01, 2.38962942e-01, 2.40258806e-01,
       2.41454498e-01, 2.43816111e-01, 2.43960656e-01, 2.46512920e-01,
       2.46724620e-01, 2.49917882e-01, 2.50025127e-01, 2.50066451e-01,
       2.52195151e-01, 2.53066531e-01, 2.56680067e-01, 2.58222975e-01,
       2.59915235e-01, 2.69461351e-01, 2.77480500e-01, 2.78620580e-01,
       2.79363681e-01, 2.80940527e-01, 2.84863915e-01, 2.87214320e-01,
       2.89575647e-01, 2.92701519e-01, 3.03743083e-01, 3.06677155e-01,
       3.09046920e-01, 3.09493204e-01, 3.11099522e-01, 3.11483281e-01,
       3.21807128e-01, 3.21921700e-01, 3.25436612e-01, 3.26950087e-01,
       3.33486051e-01, 3.34487735e-01, 3.35163664e-01, 3.42013097e-01,
       3.45066277e-01, 3.46831874e-01, 3.48618096e-01, 3.51935580e-01,
       3.59681613e-01, 3.66208300e-01, 3.70217902e-01, 3.71068391e-01,
       3.76942751e-01, 3.77419058e-01, 3.85481289e-01, 3.88283074e-01,
       3.91209734e-01, 3.92663033e-01, 3.96737727e-01, 3.97779099e-01,
       4.09300038e-01, 4.09421769e-01, 4.10128156e-01, 4.17121507e-01,
       4.19819847e-01, 4.22654433e-01, 4.30789466e-01, 4.44922187e-01,
       4.50960277e-01, 4.51688864e-01, 4.53847382e-01, 4.57616480e-01,
       4.61410396e-01, 4.68746998e-01, 4.80122203e-01, 4.92249010e-01,
       4.92651824e-01, 5.06489401e-01, 5.10826596e-01, 5.13433829e-01,
       5.15651250e-01, 5.18422302e-01, 5.24301239e-01, 5.37899244e-01,
       5.39016727e-01, 5.60643796e-01, 5.63045130e-01, 5.81194471e-01,
       5.93875542e-01, 5.93977333e-01, 5.97077059e-01, 6.12377862e-01,
       6.35932494e-01, 6.69946675e-01, 6.74557445e-01, 6.84784957e-01,
       6.95591171e-01, 7.00285799e-01, 7.05710720e-01, 7.13269334e-01,
       7.28458302e-01, 7.34424975e-01, 7.38405507e-01, 7.54434530e-01,
       7.56203875e-01, 7.70239848e-01, 7.96579707e-01, 7.98604988e-01,
       7.99871472e-01, 8.12235427e-01, 8.17674776e-01, 8.34875997e-01,
       9.30105655e-01, 9.35934241e-01, 9.35936744e-01, 1.03857176e+00,
       1.07440332e+00, 1.07892673e+00, 1.10315846e+00, 1.12898546e+00,
       1.13778257e+00, 1.16184570e+00, 1.17108371e+00, 1.25278971e+00,
       1.34561968e+00, 1.36624157e+00, 1.39808411e+00, 1.42638106e+00,
       1.65488216e+00, 1.69157485e+00, 1.86605076e+00, 2.79435800e+00,
       5.55821776e+00])

In [42]:
model.save_model(fname="cat_info_10_20_66.cbm", format="cbm")

In [44]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2

k_best = SelectKBest(chi2, k=15000)
X_new = k_best.fit_transform(df_encoded.drop(columns=["sample", "value"]), y)
X_new = pd.DataFrame(X_new, columns = k_best.get_feature_names_out())
X_new

NameError: name 'df_encoded' is not defined

In [ ]:
X_train_new, X_test_new, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

# Создание и обучение модели CatBoost
model_new = CatBoostRegressor(iterations=1200,  # количество итераций
                          learning_rate=0.15,  # скорость обучения
                          depth=7,  # глубина деревьев
                          eval_metric='MAE',  # метрика для оценки
                          verbose=100)  # вывод информации каждые 100 итераций

model_new.fit(X_train, y_train)

# Прогнозирование на тестовой выборке
y_pred = model_new.predict(X_test)

# Расчет метрик
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Вывод результатов
print(f'Mean Absolute Error (MAE): {mae:.2f}')
print(f'R² Score: {r2:.4f}')

0:	learn: 11.8707747	total: 2.84s	remaining: 47m 21s

KeyboardInterrupt:

In [24]:
year_to_file = {
    2015: "temp_data/2015.csv",
    2016: "temp_data/2016.csv",
    2017: "temp_data/2017.csv",
    2019: "temp_data/2019.csv",
    2020: "temp_data/2020.csv",
    2021: "temp_data/2021.csv",
    2022: "temp_data/2022.csv",
    2023: "temp_data/2023.csv"
}

tables = []
for year in year_to_file.keys():
    data = pd.read_csv(year_to_file[year]).drop(columns=["Unnamed: 0"])

    # Разделение даты на день и месяц
    data["Месяц"] = data["дата"].astype(str).str.split(".").str[1].astype(int)
    data["День"] = data["дата"].astype(str).str.split(".").str[0].astype(int)
    data["Год"] = year
    
    # Создание нового столбца "Дата" из дня, месяца и года
    data["Дата"] = pd.to_datetime(data["Год"].astype(str)+"-"+data["Месяц"].astype(str)+"-"+data["День"].astype(str),
               format='%Y-%m-%d', errors='coerce')
    
    # Преобразование "Время (UTC)" из float в часы и минуты
    data["Часы"] = data["Время  (UTC)"].astype(int)  # Целая часть - часы
    data["Минуты"] = ((data["Время  (UTC)"] - data["Часы"]) * 60).astype(int)  # Дробная часть - минуты

    # Создание нового столбца "Дата и Время"
    data["Дата и Время"] = data["Дата"] + pd.to_timedelta(data["Часы"], unit='h') + pd.to_timedelta(data["Минуты"], unit='m')

    # Указание города
    data["Город"] = "Воронеж" if year < 2018 else "Курск"

    # Удаление ненужных столбцов
    data.drop(columns=["дата"], inplace=True)
    
    # Добавление таблицы в список
    tables.append(data)

# Объединение всех таблиц в одну, если это необходимо
final_data = pd.concat(tables, ignore_index=True)

final_data.head()

,Время (UTC),Ветер,"(напр.,м/с)",Видим.,Явления,Облачность,Т(С),Тd(С),f(%),Тe(С),...,R24(мм),S(см),Месяц,День,Год,Дата,Часы,Минуты,Дата и Время,Город
0,0.0,В,2,10 км,{ливн. осадки},6/6 600 м[Cb calv],13.7,9.0,73.0,13.0,...,NaN,NaN,5,1,2015,2015-05-01,0,0,2015-05-01 00:00:00,Воронеж
1,3.0,В,3,10 км,слаб. ливневой дождь,10/10 300 м[Cb calv],12.3,10.6,89.0,11.0,...,NaN,NaN,5,1,2015,2015-05-01,3,0,2015-05-01 03:00:00,Воронеж
2,6.0,ЮВ,4,10 км,{ливн. осадки},10/10 300 м[Cb calv],13.3,11.6,89.0,12.0,...,NaN,NaN,5,1,2015,2015-05-01,6,0,2015-05-01 06:00:00,Воронеж
3,9.0,Ю,4,10 км,NaN,8/6 600 м[Cu hum Ci fib],18.4,11.9,66.0,19.0,...,NaN,NaN,5,1,2015,2015-05-01,9,0,2015-05-01 09:00:00,Воронеж
4,12.0,Ю,4-11 {11},10 км,NaN,5/3 600 м[Cb calv Ci sp],21.2,10.2,49.0,23.0,...,NaN,NaN,5,1,2015,2015-05-01,12,0,2015-05-01 12:00:00,Воронеж

In [25]:
final_data.to_csv("time_info.csv", index=False)