In [1]:
import numpy as np
import pandas as pd

In [ ]:
phenotypes_data=pd.read_csv('agrocodehub_data/phenotypes.tsv',sep='\t')
vegetation_data=pd.read_csv('agrocodehub_data/vegetation.tsv',sep='\t')

In [ ]:
phenotypes_data.head()

     sample  2015  2016   2017   2019   2020  2021  2022  2023
0  PS000196   NaN   NaN    NaN   99.0    NaN   NaN   NaN   NaN
1  PS000195   NaN   NaN    NaN  100.0    NaN   NaN   NaN   NaN
2  PS000121   NaN   NaN  101.0  107.0    NaN   NaN   NaN   NaN
3  PS000126   NaN   NaN    NaN  115.0  112.0   NaN   NaN   NaN
4  PS000123   NaN   NaN    NaN  113.0  102.0  79.0   NaN   NaN

In [ ]:
vegetation_data.head()

     sample  vegetation
0  PS000196         100
1  PS000195         103
2  PS000121         104
3  PS000126         106
4  PS000123         101

In [ ]:
phenotypes_data

      sample   2015  2016   2017   2019   2020   2021  2022  2023
0   PS000196    NaN   NaN    NaN   99.0    NaN    NaN   NaN   NaN
1   PS000195    NaN   NaN    NaN  100.0    NaN    NaN   NaN   NaN
2   PS000121    NaN   NaN  101.0  107.0    NaN    NaN   NaN   NaN
3   PS000126    NaN   NaN    NaN  115.0  112.0    NaN   NaN   NaN
4   PS000123    NaN   NaN    NaN  113.0  102.0   79.0   NaN   NaN
..       ...    ...   ...    ...    ...    ...    ...   ...   ...
94  PS000370    NaN   NaN    NaN    NaN    NaN  128.0  85.0   NaN
95  PS000184  101.0  98.0   95.0   95.0   79.0   95.0   NaN   NaN
96  PS000169  122.0   NaN  121.0  120.0  151.0    NaN   NaN   NaN
97  PS000053    NaN   NaN  105.0   98.0    NaN    NaN   NaN   NaN
98  PS000200    NaN   NaN    NaN  100.0    NaN    NaN   NaN   NaN

[99 rows x 9 columns]

In [ ]:
vegetation_data

      sample  vegetation
0   PS000196         100
1   PS000195         103
2   PS000121         104
3   PS000126         106
4   PS000123         101
..       ...         ...
95  PS000370         118
96  PS000184         102
97  PS000169         114
98  PS000053         119
99  PS000200         116

[100 rows x 2 columns]

In [ ]:
set(vegetation_data["sample"].unique()) - set(phenotypes_data["sample"].unique())

{'PS000368'}

In [ ]:
data = pd.merge(phenotypes_data, vegetation_data, on=["sample"])
data

      sample   2015  2016   2017   2019   2020   2021  2022  2023  vegetation
0   PS000196    NaN   NaN    NaN   99.0    NaN    NaN   NaN   NaN         100
1   PS000195    NaN   NaN    NaN  100.0    NaN    NaN   NaN   NaN         103
2   PS000121    NaN   NaN  101.0  107.0    NaN    NaN   NaN   NaN         104
3   PS000126    NaN   NaN    NaN  115.0  112.0    NaN   NaN   NaN         106
4   PS000123    NaN   NaN    NaN  113.0  102.0   79.0   NaN   NaN         101
..       ...    ...   ...    ...    ...    ...    ...   ...   ...         ...
94  PS000370    NaN   NaN    NaN    NaN    NaN  128.0  85.0   NaN         118
95  PS000184  101.0  98.0   95.0   95.0   79.0   95.0   NaN   NaN         102
96  PS000169  122.0   NaN  121.0  120.0  151.0    NaN   NaN   NaN         114
97  PS000053    NaN   NaN  105.0   98.0    NaN    NaN   NaN   NaN         119
98  PS000200    NaN   NaN    NaN  100.0    NaN    NaN   NaN   NaN         116

[99 rows x 10 columns]

In [ ]:
data.describe()

,2015,2016,2017,2019,2020,2021,2022,2023,vegetation
count,43.000000,34.000000,39.000000,81.000000,67.000000,61.000000,19.000000,15.000000,99.000000
mean,106.790698,99.911765,100.615385,101.679012,105.164179,108.721311,104.368421,104.533333,107.717172
std,15.905312,14.924797,13.548384,16.977800,17.716280,14.740117,10.414789,14.730273,5.562338
min,71.000000,69.000000,73.000000,72.000000,59.000000,67.000000,84.000000,69.000000,93.000000
25%,99.500000,92.000000,94.500000,93.000000,94.500000,102.000000,99.000000,97.500000,104.000000
50%,108.000000,102.000000,102.000000,99.000000,106.000000,108.000000,106.000000,107.000000,108.000000
75%,116.500000,112.000000,106.500000,107.000000,116.000000,119.000000,113.500000,113.500000,112.000000
max,140.000000,123.000000,124.000000,180.000000,151.000000,141.000000,116.000000,130.000000,127.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sample      99 non-null     object
 1   2015        43 non-null     float64
 2   2016        34 non-null     float64
 3   2017        39 non-null     float64
 4   2019        81 non-null     float64
 5   2020        67 non-null     float64
 6   2021        61 non-null     float64
 7   2022        19 non-null     float64
 8   2023        15 non-null     float64
 9   vegetation  99 non-null     int64
dtypes: float64(8), int64(1), object(1)
memory usage: 7.9+ KB

In [ ]:
!pip install bioinfokit

Requirement already satisfied: bioinfokit in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.1.4)
Requirement already satisfied: pandas in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (2.2.2)
Requirement already satisfied: numpy in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (1.26.4)
Requirement already satisfied: matplotlib in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (3.9.2)
Requirement already satisfied: scipy in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (1.14.1)
Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (1.5.2)
Requirement already satisfied: seaborn in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (0.13.2)
Requirement already satisfied: matplotlib-venn in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (1.1.1)
Requirement already satisfied: tabulate in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (0.9.0)
Requirement already satisfied: statsmodels in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (0.14.4)
Requirement already satisfied: textwrap3 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (0.9.2)
Requirement already satisfied: adjustText in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from bioinfokit) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->bioinfokit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas->bioinfokit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas->bioinfokit) (2024.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn->bioinfokit) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn->bioinfokit) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from statsmodels->bioinfokit) (0.5.6)
Requirement already satisfied: six in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from patsy>=0.5.6->statsmodels->bioinfokit) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
from bioinfokit.analys import marker

# id is for column name with chromosome identifier in VCF file
vcf_iter = marker.vcfreader(file='agrocodehub_data/genotypes.vcf', id='#CHROM')

header_list = []
info_lines_list = []
marker_lines_list = []

# read vcf file
for record in vcf_iter:

    # get info lines, header, and variant records
    headers, info_lines, marker_lines = record

    header_list.append(headers)
    info_lines_list.append(info_lines)
    marker_lines_list.append(marker_lines)

In [ ]:
header_list = header_list[0]
info_lines_list = info_lines_list[0]

In [ ]:
info_lines_list[-24:]

['##contig=<ID=KZ848287,length=1002>',
 '##ALT=<ID=*,Description="Represents allele(s) other than observed.">',
 '##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">',
 '##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of raw reads supporting an indel">',
 '##INFO=<ID=IMF,Number=1,Type=Float,Description="Maximum fraction of raw reads supporting an indel">',
 '##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">',
 '##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">',
 '##INFO=<ID=RPB,Number=1,Type=Float,Description="Mann-Whitney U test of Read Position Bias (bigger is better)">',
 '##INFO=<ID=MQB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality Bias (bigger is better)">',
 '##INFO=<ID=BQB,Number=1,Type=Float,Description="Mann-Whitney U test of Base Quality Bias (bigger is better)">',
 '##INFO=<ID=MQSB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality vs Strand Bias (bigger is better)">',
 '##INFO=<ID=SGB,Number=1,Type=Float,Description="Segregation based metric.">',
 '##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">',
 '##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">',
 '##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Number of high-quality bases">',
 '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">',
 '##INFO=<ID=ICB,Number=1,Type=Float,Description="Inbreeding Coefficient Binomial test (bigger is better)">',
 '##INFO=<ID=HOB,Number=1,Type=Float,Description="Bias in the number of HOMs number (smaller is better)">',
 '##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">',
 '##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">',
 '##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">',
 '##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">',
 '##bcftools_callVersion=1.10.2+htslib-1.10.2-3ubuntu0.1',
 '##bcftools_concatVersion=1.10.2+htslib-1.10.2-3ubuntu0.1']

In [ ]:
# Создание словаря
contig_dict = {}

for contig in info_lines_list[3:-23]:
    # Извлечение ID и length
    id_part = contig.split(',')[0].split('=')[2]  # Получаем ID
    length_part = contig.split(',')[1].split('=')[1][:-1]  # Получаем length
    contig_dict[id_part] = int(length_part)  # Добавляем в словарь

In [ ]:
genotypes_data = pd.DataFrame(data=marker_lines_list, columns=header_list)
genotypes_data

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,PS000026,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
0,1,40481,.,G,A,132,.,.,GT:PL:DP,"0/0:0,3,39:1",...,"0/0:0,3,48:1","./.:0,0,0:0","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,9,151:3","0/0:0,27,220:9","0/0:0,66,250:22","0/0:0,47,247:20","0/0:0,99,251:33","0/0:0,60,250:20"
1,1,40522,.,C,T,999,.,.,GT:PL:DP,"0/0:0,3,40:1",...,"0/0:0,3,25:1","./.:0,0,0:0","0/0:0,3,37:1","0/0:0,3,37:1","0/0:0,9,92:3","0/0:0,27,170:9","0/0:0,66,196:22","0/0:0,47,193:20","0/0:0,99,199:33","0/0:0,57,195:19"
2,1,111641,.,G,C,999,.,.,GT:PL:DP,"0/1:39,3,0:1",...,"./.:0,0,0:0","0/1:48,3,0:1","0/1:255,0,24:12","0/1:191,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,223:56","0/0:0,21,254:7","0/1:255,0,194:37","0/0:0,39,255:13"
3,1,111675,.,G,C,999,.,.,GT:PL:DP,"0/1:49,3,0:1",...,"./.:0,0,0:0","0/1:60,3,0:1","0/1:255,0,24:12","0/1:197,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,221:56","0/0:0,21,254:7","0/1:255,0,229:38","0/0:0,39,255:13"
4,1,111688,.,T,C,999,.,.,GT:PL:DP,"0/1:40,3,0:1",...,"./.:0,0,0:0","0/1:60,3,0:1","0/1:255,0,24:12","0/1:197,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,223:56","0/0:0,21,254:7","0/1:255,0,226:38","0/0:0,39,255:13"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38935,KZ848124,2425,.,T,A,999,.,.,GT:PL:DP,"0/1:32,0,123:7",...,"0/1:55,0,151:14","0/1:103,0,131:12","0/1:166,0,151:42","0/1:100,0,129:13","0/1:166,0,146:34","0/0:0,33,41:11","0/1:153,0,87:37","0/1:165,0,143:80","0/1:158,0,163:51","0/1:161,0,191:83"
38936,KZ848124,2494,.,T,C,999,.,.,GT:PL:DP,"0/1:35,0,159:7",...,"0/1:58,0,252:14","0/1:110,0,205:12","0/1:232,0,255:42","0/1:127,0,193:12","0/1:178,0,255:35","./.:0,0,0:0","0/1:175,0,255:103","0/1:222,0,255:121","0/1:132,0,255:76","0/1:176,0,255:134"
38937,KZ848124,2502,.,T,A,999,.,.,GT:PL:DP,"0/0:0,21,150:7",...,"0/0:0,42,255:14","0/1:51,0,205:12","0/0:0,126,255:42","0/1:59,0,207:12","0/0:0,105,255:35","0/0:0,6,8:2","0/0:0,255,255:103","0/0:0,255,255:122","0/0:0,32,255:77","0/0:0,255,255:134"
38938,KZ848124,2515,.,G,T,999,.,.,GT:PL:DP,"0/0:0,21,149:7",...,"0/1:27,0,239:14","0/0:0,36,255:12","0/0:0,32,255:42","0/1:59,0,209:12","0/0:0,57,255:35","0/0:0,6,9:2","0/0:0,54,255:103","0/1:41,0,250:122","0/0:0,14,255:76","0/1:56,0,255:134"
38939,KZ848124,2552,.,A,C,999,.,.,GT:PL:DP,"0/1:15,0,124:7",...,"0/1:55,0,151:14","0/1:103,0,131:12","0/1:164,0,146:42","0/1:103,0,131:12","0/1:165,0,150:35","0/0:6,6,0:3","0/1:161,0,173:103","0/1:171,0,172:122","0/1:117,0,156:77","0/1:126,0,168:117"

In [ ]:
genotypes_data.drop(columns=["ID", "FILTER", "INFO", "FORMAT"], inplace=True)

In [ ]:
genotypes_data.iloc[:, :5].describe()

       #CHROM       POS    REF    ALT   QUAL
count   38940     38940  38940  38940  38940
unique    110     38897   1429   1489   1019
top        18  10146005      G      T    999
freq     2740         3   9554  10150  35337

In [ ]:
genotypes_data.head()

,#CHROM,POS,REF,ALT,QUAL,PS000026,PS000027,PS000028,PS000031,PS000033,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
0,1,40481,G,A,132,"0/0:0,3,39:1","0/0:0,9,89:3","0/0:3,0,120:8","0/0:0,39,203:13","0/1:10,0,115:11",...,"0/0:0,3,48:1","./.:0,0,0:0","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,9,151:3","0/0:0,27,220:9","0/0:0,66,250:22","0/0:0,47,247:20","0/0:0,99,251:33","0/0:0,60,250:20"
1,1,40522,C,T,999,"0/0:0,3,40:1","0/1:21,0,85:4","0/1:115,0,172:22","0/0:0,57,212:19","0/1:149,0,172:31",...,"0/0:0,3,25:1","./.:0,0,0:0","0/0:0,3,37:1","0/0:0,3,37:1","0/0:0,9,92:3","0/0:0,27,170:9","0/0:0,66,196:22","0/0:0,47,193:20","0/0:0,99,199:33","0/0:0,57,195:19"
2,1,111641,G,C,999,"0/1:39,3,0:1","1/1:122,12,0:4","0/1:52,0,123:7","0/0:0,24,176:8","0/0:0,9,97:3",...,"./.:0,0,0:0","0/1:48,3,0:1","0/1:255,0,24:12","0/1:191,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,223:56","0/0:0,21,254:7","0/1:255,0,194:37","0/0:0,39,255:13"
3,1,111675,G,C,999,"0/1:49,3,0:1","1/1:150,12,0:4","0/1:64,0,186:7","0/0:0,24,255:8","0/0:0,9,151:3",...,"./.:0,0,0:0","0/1:60,3,0:1","0/1:255,0,24:12","0/1:197,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,221:56","0/0:0,21,254:7","0/1:255,0,229:38","0/0:0,39,255:13"
4,1,111688,T,C,999,"0/1:40,3,0:1","1/1:118,12,0:4","0/1:68,0,195:7","0/0:0,24,223:8","0/0:0,9,131:3",...,"./.:0,0,0:0","0/1:60,3,0:1","0/1:255,0,24:12","0/1:197,0,42:6","0/1:137,0,96:5","0/0:0,15,212:5","0/1:255,0,223:56","0/0:0,21,254:7","0/1:255,0,226:38","0/0:0,39,255:13"

In [ ]:
genotypes_data.to_csv("genotypes_processed.csv", index=False)

In [ ]:
genotypes_data["PS000433"].str.split(":").str[0].unique()

array(['0/0', './.', '0/1', '1/1', '1/2', '0/2', '1/3', '2/2', '0/3'],
      dtype=object)

In [ ]:
genotypes_data[genotypes_data["QUAL"].astype(float) < 100]

,#CHROM,POS,REF,ALT,QUAL,PS000026,PS000027,PS000028,PS000031,PS000033,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
149,1,3599872,CAAAAAAAA,CAAAAAAAAA,80,"0/0:0,3,12:1","0/0:0,24,52:8","0/0:0,114,62:38","0/0:0,78,68:27","1/1:36,23,0:19",...,"0/0:0,12,27:4","./.:0,0,0:0","0/0:0,96,56:32","0/0:0,18,36:6","0/0:0,90,57:30","0/0:0,187,47:62","./.:0,0,0:0","0/0:0,175,48:58","0/0:24,24,11:128","0/0:0,255,42:114"
298,1,8074821,CTCT,C,39.1211,"0/0:0,6,47:2","0/0:0,48,200:16","0/0:0,78,227:26","0/0:3,0,86:20","0/0:0,78,254:26",...,"0/0:0,27,76:9","0/0:0,6,35:2","0/0:0,7,35:8","0/0:0,33,163:11","0/0:0,60,152:20","0/1:9,0,50:8","0/0:0,111,159:38","0/0:0,99,203:34","0/0:0,102,215:34","0/0:0,22,113:17"
317,1,11292121,T,A,51,"./.:0,0,0:0","0/0:4,0,28:4","0/0:0,24,96:8","0/0:0,5,56:7","0/0:0,21,106:7",...,"./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","0/0:0,36,182:12","0/0:0,45,187:15","0/0:0,36,182:12","0/0:0,27,163:9","0/0:0,24,159:8"
326,1,13209987,A,C,91,"0/0:0,6,7:2","0/0:0,51,9:17","0/0:0,33,12:11","./.:0,0,0:0","0/0:0,75,7:25",...,"0/0:0,9,9:3","0/0:0,3,4:1","0/0:0,33,12:11","0/0:0,6,7:2","0/0:0,12,11:4","0/0:0,9,9:3","0/0:0,72,7:24","0/0:0,78,7:26","./.:0,0,0:0","./.:0,0,0:0"
442,1,18327660,G,A,50,"./.:0,0,0:0","./.:0,0,0:0","0/1:12,3,0:1","0/0:0,3,40:1","0/1:2,0,90:10",...,"./.:0,0,0:0","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,3,60:1","0/0:0,12,176:4","0/0:0,15,212:5","0/0:0,18,205:6","0/0:0,15,255:11","0/0:0,24,255:8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38346,KZ847136,567123,C,T,99,"0/1:0,3,4:1","0/1:0,3,9:1","0/0:0,6,7:2","0/0:0,18,20:6","0/0:0,5,6:11",...,"./.:0,0,0:0","./.:0,0,0:0","./.:0,0,0:0","0/1:0,3,4:1","0/1:0,1,7:2","0/1:0,3,9:1","0/1:0,3,4:1","0/1:0,3,4:1","0/0:0,15,58:5","0/1:0,3,4:1"
38359,KZ847139,286923,A,G,39.7275,"0/1:0,1,0:2","0/0:0,9,9:3","1/1:7,30,0:17","1/1:8,66,0:22","0/0:0,75,7:25",...,"1/1:6,32,0:21","1/1:1,6,0:16","1/1:1,23,0:84","1/1:2,32,0:58","1/1:3,43,0:100","0/0:0,81,5:32","1/1:9,54,0:18","0/0:0,105,6:35","0/0:0,216,9:78","1/1:1,17,0:69"
38670,KZ847789,1062,A,C,98,"0/0:0,6,60:2","0/1:8,0,40:8","0/0:0,23,102:25","0/0:0,35,117:19","0/0:0,23,161:21",...,"0/0:0,3,123:9","0/0:0,5,22:4","0/0:0,5,255:28","0/0:0,4,208:13","0/0:0,29,255:42","0/0:0,71,255:150","0/0:0,65,255:54","0/0:0,79,255:61","0/0:0,68,255:39","0/0:0,171,255:100"
38836,KZ847539,1292,C,G,43.6996,"1/1:9,9,0:3","0/1:0,1,0:2","1/1:9,9,0:3","0/0:0,4,2:7","0/1:0,3,3:3",...,"./.:0,0,0:0","0/1:0,3,4:1","0/1:0,3,3:3","1/1:4,3,0:1","1/1:4,3,0:1","./.:0,0,0:0","./.:0,0,0:0","1/1:7,6,0:2","1/1:10,48,0:16","1/1:8,16,0:11"
38910,KZ848124,549,A,T,92,"0/0:0,3,9:1","0/0:4,3,0:1","0/1:12,0,21:7","0/1:57,0,21:11","0/0:0,18,47:9",...,"1/1:31,10,0:13","0/0:0,9,9:3","0/0:0,20,2:36","0/0:2,8,0:18","0/0:0,13,1:51","./.:0,0,0:0","0/0:0,25,2:72","0/0:0,16,1:93","0/0:0,72,3:80","0/0:0,31,2:89"

# Start here!

In [2]:
genotypes_data = pd.read_csv("genotypes_processed.csv")

C:\Users\user\AppData\Local\Temp\ipykernel_27504\3591413676.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  genotypes_data = pd.read_csv("genotypes_processed.csv")

In [22]:
def set_nans(min_experiments: int, min_diff: int):
    genotypes_data_exp = genotypes_data.copy()

    for column in genotypes_data_exp.columns[5:]:
        split_data = genotypes_data_exp[column].str.split(":", expand=True)

        ids1 = split_data[2].astype(int) < min_experiments

        second_values = split_data[1].str.split(",").apply(lambda x: [int(i) for i in x] if isinstance(x, list) else [])

        second_largest = second_values.apply(lambda x: sorted(x)[-2] if len(x) > 1 else np.nan)
        ids2 = second_largest < min_diff

        genotypes_data_exp[column] = genotypes_data_exp[column].str.split(":").str[0]
        genotypes_data_exp.loc[ids1 | ids2, column] = "./."

    return genotypes_data_exp

gen_d_exp = set_nans(min_experiments=15, min_diff=20)
gen_d_exp

,#CHROM,POS,REF,ALT,QUAL,PS000026,PS000027,PS000028,PS000031,PS000033,...,PS000433,PS000436,PS000437,PS000440,PS000441,PS000444,PS000566,PS000567,PS000568,PS000570
0,1,40481,G,A,132.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/0,0/0,0/0,0/0
1,1,40522,C,T,999.0,./.,./.,0/1,0/0,0/1,...,./.,./.,./.,./.,./.,./.,0/0,0/0,0/0,0/0
2,1,111641,G,C,999.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/1,./.,0/1,./.
3,1,111675,G,C,999.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/1,./.,0/1,./.
4,1,111688,T,C,999.0,./.,./.,./.,./.,./.,...,./.,./.,./.,./.,./.,./.,0/1,./.,0/1,./.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38935,KZ848124,2425,T,A,999.0,./.,0/1,0/1,0/1,0/1,...,./.,./.,0/1,./.,0/1,./.,0/1,0/1,0/1,0/1
38936,KZ848124,2494,T,C,999.0,./.,0/1,0/1,0/1,0/1,...,./.,./.,0/1,./.,0/1,./.,0/1,0/1,0/1,0/1
38937,KZ848124,2502,T,A,999.0,./.,0/0,0/1,0/0,0/1,...,./.,./.,0/0,./.,0/0,./.,0/0,0/0,0/0,0/0
38938,KZ848124,2515,G,T,999.0,./.,0/0,./.,./.,./.,...,./.,./.,0/0,./.,0/0,./.,0/0,0/1,./.,0/1
38939,KZ848124,2552,A,C,999.0,./.,0/1,0/1,0/1,0/1,...,./.,./.,0/1,./.,0/1,./.,0/1,0/1,0/1,0/1

In [4]:
gen_d_exp.to_csv("genotypes_processed_fixed_feat_values3.csv", index=False)

In [5]:
time_data = pd.read_csv("Data.csv")
time_data = time_data[~time_data["value"].isna()]
time_data.head()

      sample  year  value
14  PS000076  2015  114.0
15  PS000033  2015  116.0
16  PS000048  2015   99.0
17  PS000191  2015   71.0
18  PS000077  2015   90.0

In [6]:
gen_to_merge = gen_d_exp.iloc[:, 5:].T.reset_index().rename(columns={"index": "sample"})
gen_to_merge.columns = gen_to_merge.columns.astype(str)
gen_to_merge

,sample,0,1,2,3,4,5,6,7,8,...,38930,38931,38932,38933,38934,38935,38936,38937,38938,38939
0,PS000026,./.,./.,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,./.,./.,./.,./.,./.,./.,./.
1,PS000027,./.,./.,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/0,0/0,0/1
2,PS000028,./.,0/1,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/1,./.,0/1
3,PS000031,./.,0/0,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/0,./.,0/1
4,PS000033,./.,0/1,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,0/0,0/1,0/1,0/1,0/1,0/1,./.,0/1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,PS000444,./.,./.,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/0,./.,./.,./.,./.,./.,./.,./.,./.
95,PS000566,0/0,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/1,...,0/0,./.,./.,0/1,0/1,0/1,0/1,0/0,0/0,0/1
96,PS000567,0/0,0/0,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/0,0/1,0/1
97,PS000568,0/0,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/1,...,0/0,0/1,./.,0/1,0/1,0/1,0/1,0/0,./.,0/1
98,PS000570,0/0,0/0,./.,./.,./.,./.,./.,./.,./.,...,0/0,0/1,0/1,0/1,0/1,0/1,0/1,0/0,0/1,0/1

In [23]:
count_dots = gen_to_merge.apply(lambda col: (col == './.').sum())
count_dots

sample     0
19        15
69        14
70        14
241        5
          ..
38927     15
38928     12
38929     14
38930     13
38931      4
Length: 497, dtype: int64

In [8]:
np.sum(count_dots) / 38940 / 99, np.sum(count_dots <= 50), np.sum(count_dots <= 33)

(0.7874165382639958, 5963, 2973)

In [24]:
gen_to_merge = gen_to_merge.loc[:, count_dots <= 25]
gen_to_merge

,sample,19,69,70,241,243,686,687,688,689,...,38883,38900,38902,38922,38925,38927,38928,38929,38930,38931
0,PS000026,1/1,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,./.,0/1,0/0,0/1,0/1,0/1,0/1,0/1,0/0,0/1
1,PS000027,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/1,0/1,0/1,0/1,0/1,./.,0/1,0/1,0/0,0/1
2,PS000028,0/1,0/1,0/1,0/0,0/1,0/1,0/1,0/1,0/1,...,0/1,0/1,0/0,0/1,0/1,0/1,0/1,0/1,0/0,0/1
3,PS000031,1/1,1/1,1/1,./.,1/1,0/1,0/1,0/1,0/1,...,./.,0/1,0/0,0/1,0/1,0/1,./.,./.,0/0,0/1
4,PS000033,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,0/1,0/1,0/1,0/1,0/1,0/0,0/1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,PS000444,0/0,0/0,0/0,0/0,1/1,0/1,0/1,0/1,0/1,...,0/0,./.,0/0,0/0,0/0,0/0,0/0,0/0,0/0,0/0
95,PS000566,1/1,1/1,1/1,0/0,1/1,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,./.,0/1,0/1,0/0,0/0,0/0,./.
96,PS000567,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/0,./.,0/0,./.,0/1,0/0,0/0,0/0,0/0,0/1
97,PS000568,0/0,0/0,0/0,0/0,0/0,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,0/1,0/1,0/1,0/1,./.,0/0,0/1
98,PS000570,1/1,0/0,0/0,0/0,1/1,0/1,0/1,0/1,0/1,...,0/0,0/1,0/0,0/0,0/1,0/0,0/0,0/0,0/0,0/1

In [10]:
weather_features = pd.read_csv("Weather features.csv").drop(index=[0,1]).rename(columns={"Unnamed: 0": "year"})
weather_features["year"] = weather_features["year"].astype(int)
weather_features

,year,Т(С),Т(С).1,Т(С).2,Т(С).3,Т(С).4,Тd(С),Тd(С).1,Тd(С).2,Тd(С).3,...,P(гПа).4,Po(гПа),Po(гПа).1,Po(гПа).2,Po(гПа).3,Po(гПа).4,T_critical_days,T_nogrowth_days,T_middling_days,T_optimal_days
2,2015,16.314113,21.207917,20.712903,19.155645,17.365000,6.395565,12.598750,13.577016,9.640726,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
3,2016,15.308065,19.803750,22.849194,22.140323,12.684167,9.516129,12.635000,13.895968,14.306452,...,1013.996250,994.500403,996.538333,993.798387,997.894758,995.515833,6.0,153.0,77.0,63.0
4,2017,13.699597,17.378750,20.678629,21.430364,14.940000,4.881452,9.879167,12.282661,12.314919,...,1020.126250,995.589919,991.655000,993.020161,998.868952,1001.658750,4.0,152.0,68.0,68.0
5,2019,16.822177,21.674583,18.652419,19.162500,14.319167,10.193145,12.939583,11.627016,10.886694,...,1016.910833,984.478629,988.383750,980.197984,987.036290,987.538333,1.0,153.0,66.0,77.0
6,2020,11.643145,20.985000,20.670565,19.255870,16.767083,5.518548,12.094167,10.802016,9.393522,...,1018.748333,982.829839,984.382083,984.293145,985.496761,989.552917,2.0,152.0,71.0,70.0
7,2021,14.677419,20.178750,23.121371,21.951210,11.343460,6.930645,13.018750,14.190323,12.776210,...,1016.192405,983.374194,985.202917,984.912097,984.665323,986.634599,6.0,152.0,69.0,65.0
8,2022,12.164113,20.039167,19.782661,22.075000,10.915063,2.420161,12.036250,13.608065,13.455242,...,1012.734728,984.718952,985.620417,984.626210,988.247177,983.189121,1.0,152.0,75.0,66.0
9,2023,14.301210,17.400000,19.855645,21.335081,16.441250,4.266129,9.677917,14.416532,15.326613,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0

In [11]:
final_dataset = pd.merge(pd.merge(time_data, gen_to_merge, on=["sample"]), weather_features, on=["year"])
final_dataset

,sample,year,value,19,69,70,241,243,686,687,...,P(гПа).4,Po(гПа),Po(гПа).1,Po(гПа).2,Po(гПа).3,Po(гПа).4,T_critical_days,T_nogrowth_days,T_middling_days,T_optimal_days
0,PS000076,2015,114.0,0/0,./.,./.,0/1,1/1,./.,./.,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
1,PS000033,2015,116.0,0/0,0/0,0/0,0/0,0/0,0/1,0/1,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
2,PS000048,2015,99.0,0/0,0/0,0/0,0/0,0/0,0/1,0/1,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
3,PS000191,2015,71.0,0/0,0/0,0/0,0/0,0/0,0/1,0/1,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
4,PS000077,2015,90.0,./.,0/0,0/0,0/1,1/1,./.,./.,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,PS000069,2023,102.0,0/0,0/0,0/0,0/0,0/0,0/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
355,PS000444,2023,113.0,0/0,0/0,0/0,0/0,1/1,0/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
356,PS000433,2023,119.0,0/0,0/0,0/0,0/0,1/1,0/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
357,PS000056,2023,106.0,1/1,1/1,1/1,0/0,0/0,0/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0
358,PS000436,2023,110.0,./.,./.,./.,0/0,1/1,0/1,0/1,...,1022.355417,991.049194,985.437083,981.608065,986.568548,993.235417,1.0,153.0,60.0,86.0

In [12]:
final_dataset.to_csv("final_dataset.csv", index=False)

In [25]:
X, y = final_dataset.drop(columns=["value", "sample"]), final_dataset["value"]

In [26]:
cat_features = np.array(gen_to_merge.columns[1:]).astype(str)
cat_features[:5]

array(['19', '69', '70', '241', '243'], dtype='<U5')

In [15]:
!pip install category_encoders optuna

Requirement already satisfied: category_encoders in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.6.4)
Collecting optuna
  Downloading optuna-4.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from category_encoders) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from category_encoders) (1.14.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from category_encoders) (0.14.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from category_encoders) (0.5.6)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.14.0-py3-none-any.whl.metadata (7.4 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from optuna) (24.1)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading SQLAlchemy-2.0.36-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from optuna) (4.66.5)
Collecting PyYAML (from optuna)
  Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: six in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Collecting greenlet!=0.4.17 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.1.1-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: colorama in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)
Downloading optuna-4.1.0-py3-none-any.whl (364 kB)
Downloading alembic-1.14.0-py3-none-any.whl (233 kB)
Downloading SQLAlchemy-2.0.36-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 13.0 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)
Downloading greenlet-3.1.1-cp311-cp311-win_amd64.whl (298 kB)
Downloading Mako-1.3.6-py3-none-any.whl (78 kB)
Installing collected packages: PyYAML, Mako, greenlet, colorlog, sqlalchemy, alembic, optuna
Successfully installed Mako-1.3.6 PyYAML-6.0.2 alembic-1.14.0 colorlog-6.9.0 greenlet-3.1.1 optuna-4.1.0 sqlalchemy-2.0.36

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [27]:
from category_encoders.cat_boost import CatBoostEncoder

In [28]:
cbe_encoder = CatBoostEncoder()

# Fit encoder and transform the features
cbe_encoder.fit(X.loc[:, cat_features], y)
X.loc[:, cat_features] = cbe_encoder.transform(X.loc[:, cat_features])
X.head()

,year,19,69,70,241,243,686,687,688,689,...,P(гПа).4,Po(гПа),Po(гПа).1,Po(гПа).2,Po(гПа).3,Po(гПа).4,T_critical_days,T_nogrowth_days,T_middling_days,T_optimal_days
0,2015,104.364766,103.356604,103.356604,104.790189,104.970288,102.04137,102.04137,102.04137,102.04137,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
1,2015,104.364766,104.926913,104.926913,104.016337,102.637182,104.284781,104.284781,104.284781,104.284781,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
2,2015,104.364766,104.926913,104.926913,104.016337,102.637182,104.284781,104.284781,104.284781,104.284781,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
3,2015,104.364766,104.926913,104.926913,104.016337,102.637182,104.284781,104.284781,104.284781,104.284781,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0
4,2015,105.359232,104.926913,104.926913,104.790189,104.970288,102.04137,102.04137,102.04137,102.04137,...,1019.957083,993.711694,994.912083,993.306855,1000.552016,1001.644167,4.0,153.0,74.0,69.0

In [29]:
X.columns = X.columns.astype(str)

In [21]:
import pandas as pd
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),  # Количество деревьев
        'max_depth': trial.suggest_int('max_depth', 3, 20),            # Максимальная глубина деревьев
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),  # Минимальное количество образцов для разделения узла
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),    # Минимальное количество образцов в листе
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),  # Количество признаков для поиска наилучшего разбиения
    }

    model = RandomForestRegressor(**params, random_state=42)
    model.fit(X_train.astype(float), y_train)

    y_pred = model.predict(X_test.astype(float))

    mae = mean_absolute_error(y_test, y_pred)

    return mae  # Оптимизируем по MAE

# Запуск оптимизации
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=100)

# Вывод результатов
print('Best hyperparameters:', study.best_params)
print('Best MAE:', study.best_value)

# Обучение модели с лучшими гиперпараметрами
best_params = study.best_params
best_model = RandomForestRegressor(**best_params, random_state=42)
best_model.fit(X_train.astype(float), y_train)

# Прогнозирование и расчет метрик
y_pred_best = best_model.predict(X_test.astype(float))
mae_best = mean_absolute_error(y_test, y_pred_best)
r2_best = r2_score(y_test, y_pred_best)

# Вывод результатов
print(f'Mean Absolute Error (MAE) with best params: {mae_best:.2f}')
print(f'R² Score with best params: {r2_best:.4f}')

[I 2024-11-24 14:30:45,637] A new study created in memory with name: no-name-e9383d5c-dee2-4450-a33a-c958271542de

[I 2024-11-24 14:30:45,743] Trial 0 finished with value: 10.583348400962526 and parameters: {'n_estimators': 74, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 10.583348400962526.
[I 2024-11-24 14:30:45,907] Trial 1 finished with value: 10.389944882921473 and parameters: {'n_estimators': 85, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 1 with value: 10.389944882921473.
[I 2024-11-24 14:30:46,007] Trial 2 finished with value: 10.72414875961578 and parameters: {'n_estimators': 78, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 1 with value: 10.389944882921473.
[I 2024-11-24 14:30:46,214] Trial 3 finished with value: 10.889741619241278 and parameters: {'n_estimators': 162, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 1 with value: 10.389944882921473.
[I 2024-11-24 14:30:46,470] Trial 4 finished with value: 10.375420493442384 and parameters: {'n_estimators': 159, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 4 with value: 10.375420493442384.
[I 2024-11-24 14:30:46,648] Trial 5 finished with value: 10.50360790935539 and parameters: {'n_estimators': 110, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 4 with value: 10.375420493442384.
[I 2024-11-24 14:30:46,936] Trial 6 finished with value: 10.112188801406097 and parameters: {'n_estimators': 178, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 6 with value: 10.112188801406097.
[I 2024-11-24 14:30:47,272] Trial 7 finished with value: 10.18447759872683 and parameters: {'n_estimators': 218, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 6 with value: 10.112188801406097.
[I 2024-11-24 14:30:47,592] Trial 8 finished with value: 10.277958213041465 and parameters: {'n_estimators': 228, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 6 with value: 10.112188801406097.
[I 2024-11-24 14:30:47,721] Trial 9 finished with value: 10.267412468916708 and parameters: {'n_estimators': 74, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 6 with value: 10.112188801406097.
[I 2024-11-24 14:30:48,143] Trial 10 finished with value: 10.42391779658577 and parameters: {'n_estimators': 295, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 6 with value: 10.112188801406097.
[I 2024-11-24 14:30:48,510] Trial 11 finished with value: 10.041778399770818 and parameters: {'n_estimators': 220, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 11 with value: 10.041778399770818.
[I 2024-11-24 14:30:48,872] Trial 12 finished with value: 10.100652368423644 and parameters: {'n_estimators': 220, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 11 with value: 10.041778399770818.
[I 2024-11-24 14:30:49,403] Trial 13 finished with value: 10.525862181220127 and parameters: {'n_estimators': 266, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 11 with value: 10.041778399770818.
[I 2024-11-24 14:30:49,650] Trial 14 finished with value: 10.276556959389247 and parameters: {'n_estimators': 220, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 11 with value: 10.041778399770818.
[I 2024-11-24 14:30:50,045] Trial 15 finished with value: 10.01585946142824 and parameters: {'n_estimators': 252, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:50,411] Trial 16 finished with value: 10.075037240977693 and parameters: {'n_estimators': 260, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:50,708] Trial 17 finished with value: 10.032732168311243 and parameters: {'n_estimators': 186, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:50,886] Trial 18 finished with value: 10.243605172926115 and parameters: {'n_estimators': 141, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:51,152] Trial 19 finished with value: 10.270945281747943 and parameters: {'n_estimators': 198, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:51,561] Trial 20 finished with value: 10.022985680293747 and parameters: {'n_estimators': 254, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:52,020] Trial 21 finished with value: 10.473507418515979 and parameters: {'n_estimators': 265, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:52,400] Trial 22 finished with value: 10.031205556888752 and parameters: {'n_estimators': 247, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:52,802] Trial 23 finished with value: 10.129594153035377 and parameters: {'n_estimators': 298, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:53,162] Trial 24 finished with value: 10.135463348337275 and parameters: {'n_estimators': 246, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:53,531] Trial 25 finished with value: 10.111882865536659 and parameters: {'n_estimators': 281, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:53,885] Trial 26 finished with value: 10.580592108408679 and parameters: {'n_estimators': 254, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:54,228] Trial 27 finished with value: 10.15409475694878 and parameters: {'n_estimators': 241, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:54,474] Trial 28 finished with value: 10.277709197762748 and parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:54,819] Trial 29 finished with value: 10.12949285095548 and parameters: {'n_estimators': 286, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:54,905] Trial 30 finished with value: 11.019894228788619 and parameters: {'n_estimators': 52, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:55,250] Trial 31 finished with value: 10.035708088287967 and parameters: {'n_estimators': 193, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:55,635] Trial 32 finished with value: 10.047456590973184 and parameters: {'n_estimators': 241, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:55,880] Trial 33 finished with value: 10.592838779216983 and parameters: {'n_estimators': 130, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:56,264] Trial 34 finished with value: 10.153507669482174 and parameters: {'n_estimators': 269, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:56,481] Trial 35 finished with value: 10.375070831375787 and parameters: {'n_estimators': 174, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:56,866] Trial 36 finished with value: 10.09279193634844 and parameters: {'n_estimators': 232, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:57,473] Trial 37 finished with value: 10.604792388641616 and parameters: {'n_estimators': 279, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:57,772] Trial 38 finished with value: 10.116643759747022 and parameters: {'n_estimators': 205, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:58,018] Trial 39 finished with value: 10.864991979996539 and parameters: {'n_estimators': 183, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 15 with value: 10.01585946142824.
[I 2024-11-24 14:30:58,290] Trial 40 finished with value: 9.932736298785336 and parameters: {'n_estimators': 113, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:30:58,462] Trial 41 finished with value: 10.182862332145486 and parameters: {'n_estimators': 93, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:30:58,631] Trial 42 finished with value: 10.33043027272612 and parameters: {'n_estimators': 103, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:30:58,908] Trial 43 finished with value: 10.439087392566698 and parameters: {'n_estimators': 147, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:30:59,266] Trial 44 finished with value: 10.048383258479411 and parameters: {'n_estimators': 169, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:30:59,457] Trial 45 finished with value: 10.190212134524549 and parameters: {'n_estimators': 126, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:30:59,879] Trial 46 finished with value: 10.093270531406047 and parameters: {'n_estimators': 230, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:00,425] Trial 47 finished with value: 10.636186178201346 and parameters: {'n_estimators': 249, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:00,542] Trial 48 finished with value: 10.143735113520991 and parameters: {'n_estimators': 56, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:00,749] Trial 49 finished with value: 10.897989252559535 and parameters: {'n_estimators': 158, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:01,096] Trial 50 finished with value: 10.16923574946248 and parameters: {'n_estimators': 212, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:01,421] Trial 51 finished with value: 10.018732230167792 and parameters: {'n_estimators': 183, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:01,727] Trial 52 finished with value: 10.05449366863928 and parameters: {'n_estimators': 188, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:01,927] Trial 53 finished with value: 9.945881605361642 and parameters: {'n_estimators': 119, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:02,136] Trial 54 finished with value: 9.970235216600106 and parameters: {'n_estimators': 119, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:02,337] Trial 55 finished with value: 10.043373502167405 and parameters: {'n_estimators': 121, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:02,535] Trial 56 finished with value: 10.137748546974498 and parameters: {'n_estimators': 114, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:02,673] Trial 57 finished with value: 10.289023973950274 and parameters: {'n_estimators': 85, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 40 with value: 9.932736298785336.
[I 2024-11-24 14:31:02,867] Trial 58 finished with value: 9.827313605670687 and parameters: {'n_estimators': 102, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:03,020] Trial 59 finished with value: 10.318710211253075 and parameters: {'n_estimators': 102, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:03,150] Trial 60 finished with value: 9.934962101635934 and parameters: {'n_estimators': 66, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:03,325] Trial 61 finished with value: 10.046266597789923 and parameters: {'n_estimators': 68, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:03,618] Trial 62 finished with value: 10.16566598448526 and parameters: {'n_estimators': 136, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:03,798] Trial 63 finished with value: 9.973769949676084 and parameters: {'n_estimators': 69, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:03,958] Trial 64 finished with value: 10.212126552371725 and parameters: {'n_estimators': 68, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:04,158] Trial 65 finished with value: 10.073153944980554 and parameters: {'n_estimators': 82, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:04,366] Trial 66 finished with value: 10.242860181931395 and parameters: {'n_estimators': 91, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:04,563] Trial 67 finished with value: 9.970320531160827 and parameters: {'n_estimators': 74, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:04,721] Trial 68 finished with value: 10.156431534865764 and parameters: {'n_estimators': 61, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:04,905] Trial 69 finished with value: 10.100952283405592 and parameters: {'n_estimators': 72, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:05,141] Trial 70 finished with value: 10.152453176454141 and parameters: {'n_estimators': 110, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:05,412] Trial 71 finished with value: 10.01383218791962 and parameters: {'n_estimators': 98, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:05,657] Trial 72 finished with value: 9.994862342717475 and parameters: {'n_estimators': 102, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:05,848] Trial 73 finished with value: 10.160134821944716 and parameters: {'n_estimators': 79, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:06,104] Trial 74 finished with value: 10.202341507259423 and parameters: {'n_estimators': 113, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:06,366] Trial 75 finished with value: 10.16910766208979 and parameters: {'n_estimators': 119, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:06,584] Trial 76 finished with value: 10.142484674527587 and parameters: {'n_estimators': 92, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:06,739] Trial 77 finished with value: 10.45847222784319 and parameters: {'n_estimators': 62, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 58 with value: 9.827313605670687.
[I 2024-11-24 14:31:06,961] Trial 78 finished with value: 9.85730601672595 and parameters: {'n_estimators': 85, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 58 with value: 9.827313605670687.

Best hyperparameters: {'n_estimators': 79, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'}
Best MAE: 9.80497501355887
Mean Absolute Error (MAE) with best params: 9.80
R² Score with best params: 0.2477

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Определение базовых моделей
base_models = [
    ('rf', RandomForestRegressor(**{'n_estimators': 79, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'})),
    ('xgb', XGBRegressor(**{'learning_rate': 0.0028, 'max_depth': 11, 'min_child_weight': 9, 'subsample': 0.56, 'colsample_bytree': 0.58})),
    #('lgbm', LGBMRegressor(**{'num_leaves': 33, 'learning_rate': 0.027,
                                  #'max_depth': 10, 'min_data_in_leaf': 16, 'feature_fraction': 0.56,
                                  #'bagging_fraction': 0.69, 'bagging_freq': 10}))
]

# Определение метамодели
meta_model = CatBoostRegressor(iterations=1000, verbose=100)

# Создание стекинг-регрессора
stacking_regressor = StackingRegressor(estimators=base_models, final_estimator=meta_model)

# Обучение стекинг-регрессора
stacking_regressor.fit(X_train.astype(float), y_train)

# Прогнозирование
meta_predictions = stacking_regressor.predict(X_test.astype(float))

# Оценка модели
mae = mean_absolute_error(y_test, meta_predictions)
r2 = r2_score(y_test, meta_predictions)

# Вывод результатов
print(f'Mean Absolute Error (MAE) with stacking: {mae:.2f}')
print(f'R² Score with stacking: {r2:.4f}')

Learning rate set to 0.033614
0:	learn: 15.8521942	total: 1.11ms	remaining: 1.11s
100:	learn: 13.3335706	total: 91.6ms	remaining: 815ms
200:	learn: 12.3670627	total: 177ms	remaining: 702ms
300:	learn: 11.6026902	total: 262ms	remaining: 607ms
400:	learn: 10.7137515	total: 349ms	remaining: 522ms
500:	learn: 9.9431357	total: 428ms	remaining: 426ms
600:	learn: 9.2778389	total: 513ms	remaining: 341ms
700:	learn: 8.6548754	total: 590ms	remaining: 252ms
800:	learn: 8.1566399	total: 663ms	remaining: 165ms
900:	learn: 7.6880877	total: 743ms	remaining: 81.6ms
999:	learn: 7.2622138	total: 816ms	remaining: 0us
Mean Absolute Error (MAE) with stacking: 12.41
R² Score with stacking: -0.0842

In [ ]:
model.save_model(fname="cat_info_10_20_66.cbm", format="cbm")

In [ ]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2

k_best = SelectKBest(chi2, k=15000)
X_new = k_best.fit_transform(df_encoded.drop(columns=["sample", "value"]), y)
X_new = pd.DataFrame(X_new, columns = k_best.get_feature_names_out())
X_new

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\feature_selection\_univariate_selection.py:776: UserWarning: k=15000 is greater than n_features=14965. All the features will be returned.
  warnings.warn(

,year,Т(С),Т(С).1,Т(С).2,Т(С).3,Т(С).4,Тd(С),Тd(С).1,Тd(С).2,Тd(С).3,...,38934_0/0,38934_0/1,38935_0/0,38935_0/1,38936_0/0,38936_0/1,38937_0/0,38937_0/1,38939_0/0,38939_0/1
0,2015.0,16.314113,21.207917,20.712903,19.155645,17.36500,6.395565,12.598750,13.577016,9.640726,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015.0,16.314113,21.207917,20.712903,19.155645,17.36500,6.395565,12.598750,13.577016,9.640726,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
2,2015.0,16.314113,21.207917,20.712903,19.155645,17.36500,6.395565,12.598750,13.577016,9.640726,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
3,2015.0,16.314113,21.207917,20.712903,19.155645,17.36500,6.395565,12.598750,13.577016,9.640726,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
4,2015.0,16.314113,21.207917,20.712903,19.155645,17.36500,6.395565,12.598750,13.577016,9.640726,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,2023.0,14.301210,17.400000,19.855645,21.335081,16.44125,4.266129,9.677917,14.416532,15.326613,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
355,2023.0,14.301210,17.400000,19.855645,21.335081,16.44125,4.266129,9.677917,14.416532,15.326613,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
356,2023.0,14.301210,17.400000,19.855645,21.335081,16.44125,4.266129,9.677917,14.416532,15.326613,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
357,2023.0,14.301210,17.400000,19.855645,21.335081,16.44125,4.266129,9.677917,14.416532,15.326613,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
358,2023.0,14.301210,17.400000,19.855645,21.335081,16.44125,4.266129,9.677917,14.416532,15.326613,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0

In [ ]:
X_train_new, X_test_new, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

# Создание и обучение модели CatBoost
model_new = CatBoostRegressor(iterations=1000,  # количество итераций
                          learning_rate=0.1,  # скорость обучения
                          depth=6,  # глубина деревьев
                          eval_metric='MAE',  # метрика для оценки
                          verbose=100)  # вывод информации каждые 100 итераций

model_new.fit(X_train, y_train)

# Прогнозирование на тестовой выборке
y_pred = model_new.predict(X_test)

# Расчет метрик
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Вывод результатов
print(f'Mean Absolute Error (MAE): {mae:.2f}')
print(f'R² Score: {r2:.4f}')

0:	learn: 11.8707747	total: 2.84s	remaining: 47m 21s

KeyboardInterrupt:

In [ ]:
year_to_file = {
    2015: "temp_data/2015.csv",
    2016: "temp_data/2016.csv",
    2017: "temp_data/2017.csv",
    2019: "temp_data/2019.csv",
    2020: "temp_data/2020.csv",
    2021: "temp_data/2021.csv",
    2022: "temp_data/2022.csv",
    2023: "temp_data/2023.csv"
}

tables = []
for year in year_to_file.keys():
    data = pd.read_csv(year_to_file[year]).drop(columns=["Unnamed: 0"])

    # Разделение даты на день и месяц
    data["Месяц"] = data["дата"].astype(str).str.split(".").str[1].astype(int)
    data["День"] = data["дата"].astype(str).str.split(".").str[0].astype(int)
    data["Год"] = year

    # Создание нового столбца "Дата" из дня, месяца и года
    data["Дата"] = pd.to_datetime(data["Год"].astype(str)+"-"+data["Месяц"].astype(str)+"-"+data["День"].astype(str),
               format='%Y-%m-%d', errors='coerce')

    # Преобразование "Время (UTC)" из float в часы и минуты
    data["Часы"] = data["Время  (UTC)"].astype(int)  # Целая часть - часы
    data["Минуты"] = ((data["Время  (UTC)"] - data["Часы"]) * 60).astype(int)  # Дробная часть - минуты

    # Создание нового столбца "Дата и Время"
    data["Дата и Время"] = data["Дата"] + pd.to_timedelta(data["Часы"], unit='h') + pd.to_timedelta(data["Минуты"], unit='m')

    # Указание города
    data["Город"] = "Воронеж" if year < 2018 else "Курск"

    # Удаление ненужных столбцов
    data.drop(columns=["дата"], inplace=True)

    # Добавление таблицы в список
    tables.append(data)

# Объединение всех таблиц в одну, если это необходимо
final_data = pd.concat(tables, ignore_index=True)

final_data.head()

,Время (UTC),Ветер,"(напр.,м/с)",Видим.,Явления,Облачность,Т(С),Тd(С),f(%),Тe(С),...,R24(мм),S(см),Месяц,День,Год,Дата,Часы,Минуты,Дата и Время,Город
0,0.0,В,2,10 км,{ливн. осадки},6/6 600 м[Cb calv],13.7,9.0,73.0,13.0,...,NaN,NaN,5,1,2015,2015-05-01,0,0,2015-05-01 00:00:00,Воронеж
1,3.0,В,3,10 км,слаб. ливневой дождь,10/10 300 м[Cb calv],12.3,10.6,89.0,11.0,...,NaN,NaN,5,1,2015,2015-05-01,3,0,2015-05-01 03:00:00,Воронеж
2,6.0,ЮВ,4,10 км,{ливн. осадки},10/10 300 м[Cb calv],13.3,11.6,89.0,12.0,...,NaN,NaN,5,1,2015,2015-05-01,6,0,2015-05-01 06:00:00,Воронеж
3,9.0,Ю,4,10 км,NaN,8/6 600 м[Cu hum Ci fib],18.4,11.9,66.0,19.0,...,NaN,NaN,5,1,2015,2015-05-01,9,0,2015-05-01 09:00:00,Воронеж
4,12.0,Ю,4-11 {11},10 км,NaN,5/3 600 м[Cb calv Ci sp],21.2,10.2,49.0,23.0,...,NaN,NaN,5,1,2015,2015-05-01,12,0,2015-05-01 12:00:00,Воронеж

In [ ]:
final_data.to_csv("time_info.csv", index=False)